import CryptoJS from "crypto-js";

// Array of 16 zero-width unicode characters to map hex values (0-f)
const ZW_MAP = [
  "\u200B", // 0
  "\u200C", // 1
  "\u200D", // 2
  "\u200E", // 3
  "\u200F", // 4
  "\u202A", // 5
  "\u202B", // 6
  "\u202C", // 7
  "\u202D", // 8
  "\u202E", // 9
  "\u2060", // a
  "\u2061", // b
  "\u2062", // c
  "\u2063", // d
  "\u2064", // e
  "\uFEFF", // f
];

const ZW_MAP_REV: Record<string, string> = Object.fromEntries(
  ZW_MAP.map((char, index) => [char, index.toString(16)])
);

/**
 * Embeds a zero-width unicode string containing the SHA256 hash of the userId and timestamp
 * into the given content for source tracking.
 */
export function embedMarker(
  content: string,
  userId: string,
  timestamp: Date
): string {
  const hash = CryptoJS.SHA256(userId + timestamp.toISOString()).toString(
    CryptoJS.enc.Hex
  );
  const hiddenStr = hash
    .split("")
    .map((c) => ZW_MAP[parseInt(c, 16)])
    .join("");
  return content + hiddenStr;
}

/**
 * Extracts and decodes the embedded SHA256 hash from a string using zero-width characters.
 */
export function extractMarker(content: string): string | null {
  const chars = content.split("");
  let hash = "";
  for (const c of chars) {
    if (ZW_MAP_REV[c]) {
      hash += ZW_MAP_REV[c];
    }
  }
  return hash.length === 64 ? hash : null;
}

/**
 * Generates configuration objects for pdfmake to apply watermarks and metadata
 * ensuring exported documents are traceable.
 */
export function generatePdfWatermark(userId: string, packetId: string) {
  const hash = CryptoJS.SHA256(userId + packetId).toString(CryptoJS.enc.Hex);

  return {
    watermark: {
      text: hash,
      color: "#f8f8f8",
      opacity: 0.3,
      bold: true,
      italics: false,
      angle: 45,
      fontSize: 6,
    },
    info: {
      author: "Credit Regulator Pro",
      creator: "Credit Regulator Pro",
      keywords: `ref:${hash}`,
    },
    footer: function (currentPage: number, pageCount: number) {
      return {
        text: `Generated by Credit Regulator Pro — Ref: ${hash}`,
        fontSize: 4,
        color: "#d0d0d0",
        alignment: "right",
        margin: [0, 0, 20, 0],
      };
    },
  };
}