import { createHash } from "node:crypto";
import { sql, type Kysely, type Transaction } from "kysely";

import { db } from "./db";
import { getBureauDisputeAddress } from "./bureauDisputeAddresses";
import { BusinessRuleError } from "./endpointErrorHandler";
import { ensureDisputePacketFindingsSchema } from "./disputePacketFindingsSchema";
import type { User } from "./User";
import type { DB } from "./schema";
import { sanitizeComplianceNeutralText } from "./violationCorrectionValidation";
import {
  actionForIssue,
  buildSimpleDisputePacketContent,
  labelizeIssueType,
  maskAccountNumber,
  redactSensitiveText,
  type DisputePacketType,
  type PacketNarrative,
  type PacketNarrativeCautionLevel,
  type PacketNarrativeDisputeCategory,
  type PacketRequestedAction,
  type SimpleDisputePacketContent,
  type SimpleDisputedItemInput,
} from "./disputePacketTemplate";
import {
  formatPacketConsumerEvidenceReference,
  formatPacketDisplayValue,
  formatPacketExpectedValue,
  formatPacketFieldLabel,
} from "./disputePacketHumanization";
import { buildPacketNarrative, evaluatePacketNarrativeReadiness } from "./packetNarrative";
import { evaluateViolationPacketConfidenceGate } from "./violationPacketConfidenceGate";
import {
  resolveEvidenceLocation,
  type EvidenceLocationSummary,
} from "./evidenceLocationIndex";
import { appendEvidenceEvent } from "./evidenceEventLedger";

export interface DisputePacketRecipientInput {
  name?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
}

export interface DisputePacketBuildInput {
  packetType: DisputePacketType;
  selectedIssueIds: number[];
  recipientBureauId?: number | null;
  recipient?: DisputePacketRecipientInput;
}

export interface DisputePacketCandidate {
  issueId: number;
  tradelineId: number;
  userId: number;
  userEmail: string | null;
  userDisplayName: string | null;
  packetTypes: DisputePacketType[];
  bureauName: string | null;
  creditorCollectorName: string;
  collectionAgencyName: string | null;
  maskedAccountNumber: string;
  issueType: string;
  explanation: string;
  evidenceReference: string;
  requestedAction: PacketRequestedAction;
  needsManualReview: boolean;
  reportDate: string | null;
}

export const PACKET_READINESS_REASON_CODES = [
  "NO_FINDINGS",
  "FINDING_NOT_FOUND",
  "UNAUTHORIZED_FINDING",
  "MIXED_OWNER_SELECTION",
  "MIXED_TRADELINE_SELECTION",
  "MIXED_BUREAU_SELECTION",
  "RECIPIENT_BUREAU_MISMATCH",
  "PACKET_TYPE_UNAVAILABLE",
  "COLLECTION_AGENCY_REQUIRED",
  "DISMISSED_FINDING",
  "PARSER_UNCERTAIN",
  "NEEDS_USER_REVIEW",
  "EXTRACTION_CONFIDENCE_NOT_READY",
  "MISSING_REQUIRED_EVIDENCE",
  "MANUAL_REVIEW_REQUIRED",
  "WEAK_PACKET_NARRATIVE",
] as const;

export type PacketReadinessReasonCode = typeof PACKET_READINESS_REASON_CODES[number];

export interface PacketReadinessBlocker {
  findingId?: number;
  code: PacketReadinessReasonCode;
  message: string;
  disputeCategory?: PacketNarrativeDisputeCategory | null;
  cautionLevel?: PacketNarrativeCautionLevel | null;
  issueSummary?: string | null;
  readinessWarnings?: string[];
  readinessBlockers?: string[];
}

export interface PacketReadinessWarning {
  findingId?: number;
  code: PacketReadinessReasonCode;
  message: string;
  disputeCategory?: PacketNarrativeDisputeCategory | null;
  cautionLevel?: PacketNarrativeCautionLevel | null;
  issueSummary?: string | null;
  readinessWarnings?: string[];
  readinessBlockers?: string[];
}

export interface PacketReadinessResult {
  packetReady: boolean;
  blockers: PacketReadinessBlocker[];
  warnings: PacketReadinessWarning[];
  eligibleFindingIds: number[];
  ineligibleFindingIds: number[];
  reasonCodes: PacketReadinessReasonCode[];
}

export interface PacketReadinessIssueInput {
  issueId: number;
  userId: number | null;
  tradelineId: number | null;
  bureauId?: number | null;
  userStatus?: string | null;
  validationStatus?: string | null;
  autoGenerated?: boolean | null;
  technicalDetails?: unknown;
  evidenceReference?: string | null;
  packetTypes?: DisputePacketType[];
  packetNarrative?: PacketNarrative | null;
}

type IssueRow = {
  issueId: number;
  issueUserExplanation: string | null;
  issueRecommendedAction: string | null;
  issueViolationCategory: string | null;
  issueDisputeVector: string | null;
  issueTechnicalDetails: unknown;
  issueUserStatus: string | null;
  issueValidationStatus: string | null;
  issueAutoGenerated: boolean | null;
  tradelineId: number;
  userId: number | null;
  userEmail: string | null;
  userDisplayName: string | null;
  consumerFullName: string | null;
  consumerEmail: string | null;
  consumerAddressLine1: string | null;
  consumerAddressLine2: string | null;
  consumerCity: string | null;
  consumerProvince: string | null;
  consumerPostalCode: string | null;
  consumerPhone: string | null;
  bureauId: number | null;
  bureauName: string | null;
  bureauAddressLine1: string | null;
  bureauAddressLine2: string | null;
  bureauCity: string | null;
  bureauProvince: string | null;
  bureauPostalCode: string | null;
  creditorName: string | null;
  accountNumber: string | null;
  accountType: string | null;
  status: string | null;
  balance: string | null;
  currentBalance: string | null;
  creditLimit: string | null;
  highCredit: string | null;
  amountPastDue: string | null;
  openedDate: Date | null;
  dateClosed: Date | null;
  dateOfFirstDelinquency: Date | null;
  dateOfLastPayment: Date | null;
  lastActivityDate: Date | null;
  lastReportedDate: Date | null;
  collectionAgencyName: string | null;
  originalCreditorName: string | null;
  isCollectionAccount: boolean | null;
  reportArtifactId: number | null;
  reportArtifactData: unknown;
  reportDate: Date | null;
  sourceText: string | null;
};

export type PacketConsumerDisputedItemSource = Pick<
  IssueRow,
  | "issueId"
  | "issueUserExplanation"
  | "issueRecommendedAction"
  | "issueViolationCategory"
  | "issueDisputeVector"
  | "issueTechnicalDetails"
  | "tradelineId"
  | "accountNumber"
  | "creditorName"
  | "balance"
  | "currentBalance"
  | "creditLimit"
  | "highCredit"
  | "amountPastDue"
  | "status"
  | "openedDate"
  | "dateClosed"
  | "dateOfFirstDelinquency"
  | "dateOfLastPayment"
  | "lastActivityDate"
  | "lastReportedDate"
  | "collectionAgencyName"
  | "originalCreditorName"
  | "reportArtifactId"
  | "sourceText"
> & Partial<Pick<
  IssueRow,
  | "bureauName"
  | "consumerProvince"
  | "accountType"
  | "isCollectionAccount"
  | "reportDate"
  | "reportArtifactData"
  | "issueUserStatus"
  | "issueValidationStatus"
>>;

export type PacketInternalReferenceSource = Pick<
  IssueRow,
  | "issueId"
  | "issueTechnicalDetails"
  | "tradelineId"
  | "reportArtifactId"
  | "reportArtifactData"
  | "sourceText"
>;

export type PacketInternalReferenceMetadata = NonNullable<
  SimpleDisputePacketContent["metadata"]["internalReferences"]
>[number];

type RecipientRecord = {
  name: string;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  province: string | null;
  postalCode: string | null;
  addressLines: string[];
};

interface DisputePacketPreview {
  packet: SimpleDisputePacketContent;
  recipientRecord: RecipientRecord;
  ownerUserId: number;
  firstTradelineId: number;
  bureauId: number | null;
  selectedIssueIds: number[];
  linkedFindingId: number | null;
  issueRows: IssueRow[];
  readiness: PacketReadinessResult;
}

type PacketPersistenceExecutor = Kysely<DB> | Transaction<DB>;

export type PacketDuplicatePolicy = "created_new" | "idempotent_reuse";

export type DisputePacketCreateResult = {
  packetId: number;
  packet: SimpleDisputePacketContent;
  status: string;
  duplicatePolicy: PacketDuplicatePolicy;
  reusedExistingPacket: boolean;
  existingPacketId?: number;
};

function hashEvent(value: unknown): string {
  return createHash("sha256").update(JSON.stringify(value)).digest("hex");
}

function parseDetails(value: unknown): Record<string, unknown> {
  if (!value) return {};
  if (typeof value === "string") {
    try {
      const parsed = JSON.parse(value);
      return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {};
    } catch {
      return {};
    }
  }
  return typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

function objectValue(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null;
}

function firstText(details: Record<string, unknown>, keys: string[]): string | null {
  for (const key of keys) {
    const value = details[key];
    if (typeof value === "string" && value.trim()) return value.trim();
    if (typeof value === "number" && Number.isFinite(value)) return String(value);
  }
  return null;
}

function firstKnownText(values: Array<string | null | undefined>): string | null {
  for (const value of values) {
    if (value && value.trim()) return value.trim();
  }
  return null;
}

function toPacketDate(value: Date | null): string | null {
  if (!value) return null;
  return value.toISOString();
}

function fieldFromDetails(details: Record<string, unknown>): string | null {
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  return firstKnownText([
    firstConsumerFieldText(details, ["fieldName", "canonicalField", "field", "disputedField"]),
    evidence ? firstConsumerFieldText(evidence, ["fieldName", "field", "canonicalField", "disputedField"]) : null,
    firstConsumerFieldText(details, ["sourceField"]),
    evidence ? firstConsumerFieldText(evidence, ["sourceField", "canonicalField", "fieldKey"]) : null,
  ]);
}

function firstConsumerFieldText(details: Record<string, unknown>, keys: string[]): string | null {
  for (const key of keys) {
    const value = firstText(details, [key]);
    if (value && formatPacketFieldLabel(value) !== "Supporting reference") return value;
  }
  return null;
}

function valueFromTradeline(row: PacketConsumerDisputedItemSource, fieldName: string | null): unknown {
  const normalized = String(fieldName ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");

  if (normalized.includes("accountnumber")) return row.accountNumber;
  if (normalized.includes("balance")) return row.balance ?? row.currentBalance;
  if (normalized.includes("currentbalance")) return row.currentBalance ?? row.balance;
  if (normalized.includes("creditlimit")) return row.creditLimit;
  if (normalized.includes("highcredit")) return row.highCredit;
  if (normalized.includes("pastdue")) return row.amountPastDue;
  if (normalized.includes("status") || normalized.includes("mop")) return row.status;
  if (normalized.includes("opened")) return row.openedDate;
  if (normalized.includes("closed")) return row.dateClosed;
  if (normalized.includes("firstdelinquency")) return row.dateOfFirstDelinquency;
  if (normalized.includes("lastpayment")) return row.dateOfLastPayment;
  if (normalized.includes("lastactivity")) return row.lastActivityDate;
  if (normalized.includes("reported")) return row.lastReportedDate;
  if (normalized.includes("collectionagency")) return row.collectionAgencyName;
  return null;
}

function issueTypeForRow(row: PacketConsumerDisputedItemSource): string {
  return firstKnownText([row.issueViolationCategory, row.issueDisputeVector]) ?? "reporting_issue";
}

function evidenceReferenceForRow(row: PacketConsumerDisputedItemSource, details: Record<string, unknown>): string {
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  const reportArtifactId =
    evidence && typeof evidence.reportArtifactId === "number"
      ? evidence.reportArtifactId
      : row.reportArtifactId;
  const fieldName = firstKnownText([
    evidence ? firstText(evidence, ["fieldName", "field"]) : null,
    firstText(details, ["fieldName", "canonicalField", "field", "sourceField", "disputedField"]),
  ]);
  const pageNumber = evidence ? Number(evidence.pageNumber ?? evidence.page) : Number(details.pageNumber ?? details.page);
  const snippet = firstKnownText([
    evidence ? firstText(evidence, ["textSnippet", "excerpt"]) : null,
    firstText(details, ["textSnippet", "evidenceSnippet", "excerpt"]),
  ]);

  return formatPacketConsumerEvidenceReference({
    fieldName,
    pageNumber: Number.isFinite(pageNumber) && pageNumber > 0 ? pageNumber : null,
    excerpt: snippet,
    accountNumber: row.accountNumber,
    hasSourceReport: Boolean(reportArtifactId || row.sourceText?.trim()),
  });
}

export interface PacketEvidenceLocationSource {
  issueId: number;
  reportArtifactId?: number | null;
  reportArtifactData?: unknown;
  technicalDetails?: unknown;
}

function evidenceLocationRequestForIssue(
  source: PacketEvidenceLocationSource,
  details: Record<string, unknown>,
) {
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  return {
    reportArtifactId: evidence?.reportArtifactId ?? evidence?.sourceReportArtifactId ?? source.reportArtifactId,
    evidenceId: firstText(details, ["evidenceId", "canonicalEvidenceId"]) ??
      (evidence ? firstText(evidence, ["evidenceId", "canonicalEvidenceId"]) : null),
    fieldKey: firstText(details, ["fieldKey", "canonicalFieldKey"]) ??
      (evidence ? firstText(evidence, ["fieldKey", "canonicalFieldKey"]) : null),
    sourceField: firstText(details, ["sourceField", "canonicalField", "disputedField"]) ??
      (evidence ? firstText(evidence, ["sourceField", "canonicalField", "field"]) : null),
    fieldName: firstKnownText([
      firstText(details, ["fieldName", "canonicalField", "field", "sourceField", "disputedField"]),
      evidence ? firstText(evidence, ["fieldName", "field"]) : null,
    ]),
  };
}

type EvidenceLocationRequest = ReturnType<typeof evidenceLocationRequestForIssue>;
type EvidenceLocationLookupContext = {
  reportArtifactData?: unknown;
};

export function buildPacketEvidenceLocationsForIssues(
  sources: PacketEvidenceLocationSource[],
): Record<string, EvidenceLocationSummary[]> | undefined {
  const entries = sources
    .map((source): [string, EvidenceLocationSummary[]] | null => {
      const details = parseDetails(source.technicalDetails);
      const evidenceLocation = resolveEvidenceLocation(
        { reportArtifactData: source.reportArtifactData },
        evidenceLocationRequestForIssue(source, details),
      );
      return evidenceLocation ? [String(source.issueId), [evidenceLocation]] : null;
    })
    .filter((entry): entry is [string, EvidenceLocationSummary[]] => Boolean(entry));

  return entries.length > 0 ? Object.fromEntries(entries) : undefined;
}

function attachEvidenceLocationsToPacket(
  packet: SimpleDisputePacketContent,
  rows: IssueRow[],
): SimpleDisputePacketContent {
  const evidenceLocations = buildPacketEvidenceLocationsForIssues(
    rows.map((row) => ({
      issueId: row.issueId,
      reportArtifactId: row.reportArtifactId,
      reportArtifactData: row.reportArtifactData,
      technicalDetails: row.issueTechnicalDetails,
    })),
  );

  return evidenceLocations ? { ...packet, evidenceLocations } : packet;
}

function uniqueSortedIds(ids: number[]): number[] {
  return Array.from(new Set(ids.filter((id) => Number.isFinite(id)))).sort((left, right) => left - right);
}

function hasSameIdSet(left: number[], right: number[]): boolean {
  const normalizedLeft = uniqueSortedIds(left);
  const normalizedRight = uniqueSortedIds(right);
  return (
    normalizedLeft.length === normalizedRight.length &&
    normalizedLeft.every((id, index) => id === normalizedRight[index])
  );
}

function reportArtifactIdForRow(row: PacketInternalReferenceSource): number | null {
  const details = parseDetails(row.issueTechnicalDetails);
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  const evidenceReportArtifactId = Number(evidence?.reportArtifactId ?? evidence?.sourceReportArtifactId);
  if (Number.isInteger(evidenceReportArtifactId) && evidenceReportArtifactId > 0) return evidenceReportArtifactId;
  return row.reportArtifactId;
}

function positiveIntegerValue(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

function finiteNumberValue(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function stringIdValue(value: unknown): string | null {
  if (typeof value === "string" && value.trim()) return value.trim();
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (typeof value === "bigint") return value.toString();
  return null;
}

function sanitizedBoundingBox(value: unknown): Record<string, unknown> | null {
  const box = objectValue(value);
  if (!box) return null;
  const x = finiteNumberValue(box.x);
  const y = finiteNumberValue(box.y);
  const width = finiteNumberValue(box.width);
  const height = finiteNumberValue(box.height);
  const pageNumber = positiveIntegerValue(box.pageNumber);
  if (
    x === null ||
    y === null ||
    width === null ||
    height === null ||
    width <= 0 ||
    height <= 0 ||
    pageNumber === null ||
    box.coordinateValidated !== true
  ) {
    return null;
  }
  if (box.unit === "px" && box.coordinateSource === "tesseract_tsv_word") {
    return {
      x,
      y,
      width,
      height,
      unit: "px",
      pageNumber,
      coordinateSource: "tesseract_tsv_word",
      coordinateValidated: true,
    };
  }
  if (box.unit === "pt" && box.coordinateSource === "pdfjs_text_item") {
    return {
      x,
      y,
      width,
      height,
      unit: "pt",
      pageNumber,
      coordinateSource: "pdfjs_text_item",
      coordinateValidated: true,
    };
  }
  return null;
}

function sanitizedPageDimensions(value: unknown): Record<string, unknown> | null {
  const dimensions = objectValue(value);
  if (!dimensions) return null;
  const width = finiteNumberValue(dimensions.width);
  const height = finiteNumberValue(dimensions.height);
  if (
    width === null ||
    height === null ||
    width <= 0 ||
    height <= 0 ||
    (dimensions.unit !== "px" && dimensions.unit !== "pt")
  ) {
    return null;
  }
  return { width, height, unit: dimensions.unit };
}

function sanitizedProvenance(value: unknown): Record<string, unknown> | null {
  const provenance = objectValue(value);
  if (!provenance) return null;
  const output: Record<string, unknown> = {};
  for (const key of [
    "deterministicPipelineVersion",
    "documentBinarySha256",
    "rawTextSha256",
    "canonicalResultSha256",
    "replayHash",
    "ocrEngine",
    "ocrRenderer",
  ]) {
    const text = firstText(provenance, [key]);
    if (text) output[key] = text;
  }
  for (const key of ["ocrOverallConfidence", "ocrPageConfidence"]) {
    const parsed = finiteNumberValue(provenance[key]);
    if (parsed !== null) output[key] = parsed;
  }
  return Object.keys(output).length > 0 ? output : null;
}

function sanitizedEvidenceLocationEntry(location: unknown): Record<string, unknown> | null {
  const record = objectValue(location);
  if (!record) return null;
  const output: Record<string, unknown> = {};
  const evidenceId = stringIdValue(record.evidenceId);
  if (evidenceId) output.evidenceId = evidenceId;
  for (const key of [
    "fieldKey",
    "sourceField",
    "sourceMethod",
    "extractionMethod",
    "sectionName",
    "zoneName",
    "ruleId",
    "matchedTextHash",
    "canonicalValueHash",
    "sourceTextHash",
    "coordinateExtractorVersion",
  ]) {
    const text = firstText(record, [key]);
    if (text) output[key] = text;
  }
  const pageNumber = positiveIntegerValue(record.pageNumber);
  if (pageNumber !== null) output.pageNumber = pageNumber;
  for (const key of ["confidence", "coordinateConfidence"]) {
    const parsed = finiteNumberValue(record[key]);
    if (parsed !== null) output[key] = parsed;
  }
  const boundingBox = sanitizedBoundingBox(record.boundingBox);
  if (boundingBox) output.boundingBox = boundingBox;
  const pageDimensions = sanitizedPageDimensions(record.pageDimensions);
  if (pageDimensions) output.pageDimensions = pageDimensions;
  const provenance = sanitizedProvenance(record.provenance);
  if (provenance) output.provenance = provenance;
  return Object.keys(output).length > 0 ? output : null;
}

function sanitizedEvidenceLocationSnapshot(locations: unknown[]): Record<string, unknown>[] {
  const seen = new Set<string>();
  return locations
    .map(sanitizedEvidenceLocationEntry)
    .filter((entry): entry is Record<string, unknown> => Boolean(entry))
    .filter((entry) => {
      const key = JSON.stringify(entry);
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    });
}

function directEvidenceLocationsFromDetails(details: Record<string, unknown>): unknown[] {
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  return [
    details.evidenceLocation,
    evidence?.evidenceLocation,
    objectValue(details.deterministicRule)?.evidenceLocation,
    objectValue(objectValue(details.deterministicRule)?.evidence)?.evidenceLocation,
  ].filter((location) => objectValue(location));
}

function evidenceIdsFromDetails(details: Record<string, unknown>): string[] {
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  const directLocations = directEvidenceLocationsFromDetails(details);
  return Array.from(new Set([
    stringIdValue(details.evidenceId),
    stringIdValue(details.canonicalEvidenceId),
    evidence ? stringIdValue(evidence.evidenceId) : null,
    evidence ? stringIdValue(evidence.canonicalEvidenceId) : null,
    ...directLocations.map((location) => stringIdValue(objectValue(location)?.evidenceId)),
  ].filter((id): id is string => Boolean(id))));
}

function stringValuesFrom(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.flatMap(stringValuesFrom);
  }
  const id = stringIdValue(value);
  return id ? [id] : [];
}

function collectStringValues(records: Array<Record<string, unknown> | null | undefined>, keys: string[]): string[] {
  return Array.from(new Set(
    records.flatMap((record) => record ? keys.flatMap((key) => stringValuesFrom(record[key])) : []),
  ));
}

function internalRuleRecords(details: Record<string, unknown>): Array<Record<string, unknown> | null> {
  const deterministicRule = objectValue(details.deterministicRule);
  const evidence = objectValue(details.evidenceLink) ?? objectValue(deterministicRule?.evidence);
  return [
    details,
    deterministicRule,
    evidence,
    objectValue(details.evidenceLocation),
    objectValue(evidence?.evidenceLocation),
    objectValue(deterministicRule?.evidenceLocation),
    objectValue(objectValue(deterministicRule?.evidence)?.evidenceLocation),
  ];
}

export function buildPacketInternalReferenceMetadata(
  row: PacketInternalReferenceSource,
  readiness?: PacketReadinessResult,
): PacketInternalReferenceMetadata {
  const details = parseDetails(row.issueTechnicalDetails);
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  const records = internalRuleRecords(details);

  return {
    findingId: row.issueId,
    violationId: row.issueId,
    tradelineId: row.tradelineId,
    reportArtifactId: reportArtifactIdForRow(row),
    evidenceIds: evidenceIdsFromDetails(details),
    regulationIds: collectStringValues(records, [
      "regulationId",
      "regulationIds",
      "referenceId",
      "referenceIds",
      "legalReferenceId",
      "legalReferenceIds",
      "authorityId",
      "authorityIds",
    ]),
    ruleIds: collectStringValues(records, [
      "ruleId",
      "ruleIds",
      "deterministicRuleId",
      "runtimeRuleId",
    ]),
    fieldKey: firstText(details, ["fieldKey", "canonicalFieldKey"]) ??
      (evidence ? firstText(evidence, ["fieldKey", "canonicalFieldKey"]) : null),
    sourceField: firstText(details, ["sourceField", "canonicalField", "disputedField"]) ??
      (evidence ? firstText(evidence, ["sourceField", "canonicalField", "field"]) : null),
    readiness: readiness ? readinessSnapshotForIssue(readiness, row.issueId) : undefined,
  };
}

function resolveReportArtifactLocationByEvidenceIds(
  context: EvidenceLocationLookupContext,
  request: EvidenceLocationRequest,
  evidenceIds: string[],
): Record<string, unknown>[] {
  const locations = evidenceIds
    .map((evidenceId) =>
      resolveEvidenceLocation(
        { reportArtifactData: context.reportArtifactData },
        {
          reportArtifactId: request.reportArtifactId,
          evidenceId,
        },
      ),
    )
    .filter((location): location is EvidenceLocationSummary => Boolean(location));
  return sanitizedEvidenceLocationSnapshot(locations);
}

function resolveReportArtifactLocationByField(
  context: EvidenceLocationLookupContext,
  request: EvidenceLocationRequest,
): Record<string, unknown>[] {
  const location = resolveEvidenceLocation(
    { reportArtifactData: context.reportArtifactData },
    {
      reportArtifactId: request.reportArtifactId,
      fieldKey: request.fieldKey,
      sourceField: request.sourceField,
    },
  );
  return location ? sanitizedEvidenceLocationSnapshot([location]) : [];
}

export function buildPacketFindingEvidenceLocationSnapshot(input: {
  packet: SimpleDisputePacketContent;
  issueId: number;
  reportArtifactId?: number | null;
  reportArtifactData?: unknown;
  technicalDetails?: unknown;
}): Record<string, unknown>[] {
  const packetLocations = input.packet.evidenceLocations?.[String(input.issueId)] ?? [];
  const packetSnapshot = sanitizedEvidenceLocationSnapshot(packetLocations);
  if (packetSnapshot.length > 0) return packetSnapshot;

  const details = parseDetails(input.technicalDetails);
  const directSnapshot = sanitizedEvidenceLocationSnapshot(directEvidenceLocationsFromDetails(details));
  if (directSnapshot.length > 0) return directSnapshot;

  const source = {
    issueId: input.issueId,
    reportArtifactId: input.reportArtifactId,
    reportArtifactData: input.reportArtifactData,
    technicalDetails: input.technicalDetails,
  };
  const request = evidenceLocationRequestForIssue(source, details);
  const evidenceIds = evidenceIdsFromDetails(details);
  const evidenceIdSnapshot = resolveReportArtifactLocationByEvidenceIds(
    { reportArtifactData: input.reportArtifactData },
    request,
    evidenceIds,
  );
  if (evidenceIdSnapshot.length > 0) return evidenceIdSnapshot;

  return resolveReportArtifactLocationByField(
    { reportArtifactData: input.reportArtifactData },
    request,
  );
}

function evidenceIdsForIssue(row: IssueRow, evidenceLocations: Record<string, unknown>[]): string[] {
  const ids = evidenceLocations
    .map((location) => stringIdValue(location.evidenceId))
    .filter((evidenceId): evidenceId is string => Boolean(evidenceId));

  const details = parseDetails(row.issueTechnicalDetails);
  return Array.from(new Set([...ids, ...evidenceIdsFromDetails(details)]));
}

function readinessSnapshotForIssue(readiness: PacketReadinessResult, issueId: number): Record<string, unknown> {
  return {
    packetReady: readiness.packetReady,
    findingEligible: readiness.eligibleFindingIds.includes(issueId),
    reasonCodes: readiness.reasonCodes,
    blockerCodes: readiness.blockers
      .filter((blocker) => blocker.findingId === undefined || blocker.findingId === issueId)
      .map((blocker) => blocker.code),
    warningCodes: readiness.warnings
      .filter((warning) => warning.findingId === undefined || warning.findingId === issueId)
      .map((warning) => warning.code),
  };
}

export function attachInternalPacketMetadata(
  packet: SimpleDisputePacketContent,
  rows: PacketInternalReferenceSource[],
  readiness: PacketReadinessResult,
): SimpleDisputePacketContent {
  return {
    ...packet,
    metadata: {
      ...packet.metadata,
      internalReferences: rows.map((row) => buildPacketInternalReferenceMetadata(row, readiness)),
    },
  };
}

function packetItemSnapshotForIssue(packet: SimpleDisputePacketContent, row: IssueRow): Record<string, unknown> {
  const item = packet.disputedItems.find((candidate) => candidate.issueId === row.issueId);
  return {
    issueId: row.issueId,
    tradelineId: row.tradelineId,
    disputedField: item?.disputedField ?? null,
    issueType: item?.issueType ?? null,
    requestedAction: item?.requestedAction ?? null,
    needsManualReview: item?.needsManualReview ?? null,
    maskedAccountNumber: item?.maskedAccountNumber ?? null,
    evidenceReferenceHash: item?.evidenceReference ? hashEvent({ evidenceReference: item.evidenceReference }) : null,
  };
}

function assertPacketFindingRowsCanBeWritten(
  user: Pick<User, "id" | "role">,
  preview: DisputePacketPreview,
): void {
  const selectedIds = preview.selectedIssueIds;
  const metadataIds = preview.packet.metadata.selectedIssueIds;
  const itemIds = preview.packet.disputedItems
    .map((item) => item.issueId)
    .filter((id): id is number => typeof id === "number" && Number.isFinite(id));
  const rowIds = preview.issueRows.map((row) => row.issueId);

  if (
    !hasSameIdSet(selectedIds, metadataIds) ||
    !hasSameIdSet(selectedIds, itemIds) ||
    !hasSameIdSet(selectedIds, rowIds) ||
    !hasSameIdSet(selectedIds, preview.readiness.eligibleFindingIds)
  ) {
    throw new BusinessRuleError("Selected packet findings could not be resolved safely.");
  }

  if (user.role !== "admin" && preview.ownerUserId !== user.id) {
    throw new BusinessRuleError("Unauthorized access to disputed items.", 403);
  }

  if (preview.issueRows.some((row) => row.userId !== preview.ownerUserId)) {
    throw new BusinessRuleError("Selected packet findings do not share one owner.");
  }

  if (preview.issueRows.some((row) => row.tradelineId !== preview.firstTradelineId)) {
    throw new BusinessRuleError("Selected packet findings do not share one account.");
  }
}

function buildDisputePacketFindingRows(
  preview: DisputePacketPreview,
  packetId: number,
  statusAtCreation: string | null,
  actorUserId: number,
  now: Date,
) {
  return preview.issueRows.map((row) => {
    const evidenceLocationSnapshot = buildPacketFindingEvidenceLocationSnapshot({
      packet: preview.packet,
      issueId: row.issueId,
      reportArtifactId: reportArtifactIdForRow(row),
      reportArtifactData: row.reportArtifactData,
      technicalDetails: row.issueTechnicalDetails,
    });
    return {
      disputePacketId: packetId,
      creditorObligationTestId: row.issueId,
      reportArtifactId: reportArtifactIdForRow(row),
      tradelineId: row.tradelineId,
      userId: Number(row.userId),
      bureauId: row.bureauId,
      packetType: preview.packet.packetType,
      evidenceIds: evidenceIdsForIssue(row, evidenceLocationSnapshot) as any,
      evidenceLocationSnapshot: evidenceLocationSnapshot as any,
      readinessSnapshot: readinessSnapshotForIssue(preview.readiness, row.issueId) as any,
      packetItemSnapshot: packetItemSnapshotForIssue(preview.packet, row) as any,
      statusAtCreation,
      selectedAt: now,
      createdAt: now,
      createdBy: actorUserId,
      sourceVersion: preview.packet.version,
      backfilled: false,
    };
  });
}

function rowHasCollectionRecipient(row: IssueRow): boolean {
  return Boolean(row.collectionAgencyName?.trim());
}

function packetTypesForRow(row: IssueRow): DisputePacketType[] {
  const types: DisputePacketType[] = ["credit_bureau"];
  const issueType = issueTypeForRow(row).toUpperCase();
  if (
    rowHasCollectionRecipient(row) &&
    (row.isCollectionAccount === true ||
      issueType.includes("COLLECTOR") ||
      issueType.includes("COLLECTION") ||
      issueType.includes("PHANTOM_DEBT") ||
      issueType.includes("MULTIPLE_COLLECTOR"))
  ) {
    types.push("collection_agency");
  }
  return types;
}

function dedupeIssueIds(issueIds: number[]): number[] {
  return Array.from(new Set(issueIds.map((id) => Number(id)).filter((id) => Number.isFinite(id))));
}

function packetPersistenceType(input: DisputePacketBuildInput): string {
  return input.packetType === "collection_agency" ? "collection_agency_dispute" : "credit_bureau_dispute";
}

function selectedIssueKey(issueIds: number[]): string {
  return dedupeIssueIds(issueIds).sort((left, right) => left - right).join(",");
}

function numericId(value: unknown): number | null {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function packetIdempotencyLockParts(preview: DisputePacketPreview, packetType: string): [number, number] {
  const key = [
    "packet-create-v1",
    preview.ownerUserId,
    packetType,
    preview.firstTradelineId,
    preview.bureauId ?? "none",
    selectedIssueKey(preview.selectedIssueIds),
  ].join(":");
  const digest = createHash("sha256").update(key).digest();
  return [digest.readInt32BE(0), digest.readInt32BE(4)];
}

function hasSameSelectedIssueSet(left: number[], right: unknown[]): boolean {
  const leftKey = selectedIssueKey(left);
  const rightKey = selectedIssueKey(right.map(numericId).filter((value): value is number => value !== null));
  return leftKey === rightKey;
}

function parseExistingPacketContent(content: string | null): SimpleDisputePacketContent | null {
  if (!content) return null;
  try {
    const parsed = JSON.parse(content);
    return parsed && typeof parsed === "object" ? parsed as SimpleDisputePacketContent : null;
  } catch {
    return null;
  }
}

async function findIdempotentExistingPacket(
  executor: PacketPersistenceExecutor,
  preview: DisputePacketPreview,
  packetType: string,
): Promise<{ id: number; status: string | null; content: SimpleDisputePacketContent } | null> {
  let query = executor
    .selectFrom("packet")
    .select(["id", "status", "content"])
    .where("userId", "=", preview.ownerUserId)
    .where("tradelineId", "=", preview.firstTradelineId)
    .where("type", "=", packetType)
    .where("processingStatus", "=", "completed")
    .where("content", "is not", null)
    .orderBy("createdAt", "asc")
    .orderBy("id", "asc")
    .limit(50);

  query = preview.bureauId === null
    ? query.where("bureauId", "is", null)
    : query.where("bureauId", "=", preview.bureauId);

  const candidates = await query.execute();
  if (candidates.length === 0) return null;

  const candidateIds = candidates.map((candidate) => candidate.id);
  const findingRows = await executor
    .selectFrom("disputePacketFindings")
    .select(["disputePacketId", "creditorObligationTestId", "userId", "tradelineId", "bureauId", "packetType"])
    .where("disputePacketId", "in", candidateIds)
    .execute();

  for (const candidate of candidates) {
    const candidateId = numericId(candidate.id);
    const packetFindings = findingRows.filter((row) => numericId(row.disputePacketId) === candidateId);
    if (
      packetFindings.length > 0 &&
      hasSameSelectedIssueSet(
        preview.selectedIssueIds,
        packetFindings.map((row) => row.creditorObligationTestId),
      ) &&
      packetFindings.every((row) =>
        numericId(row.userId) === preview.ownerUserId &&
        numericId(row.tradelineId) === preview.firstTradelineId &&
        (preview.bureauId === null ? row.bureauId === null : numericId(row.bureauId) === preview.bureauId) &&
        row.packetType === preview.packet.packetType
      )
    ) {
      const content = parseExistingPacketContent(candidate.content);
      if (content) {
        return {
          id: candidate.id,
          status: candidate.status,
          content,
        };
      }
    }
  }

  return null;
}

async function writePacketIdempotentReuseAudit(
  executor: PacketPersistenceExecutor,
  params: {
    packetId: number;
    actorUserId: number;
    ownerUserId: number;
    packetType: string;
    selectedIssueIds: number[];
    linkedFindingId: number | null;
    now: Date;
  },
): Promise<void> {
  await executor
    .insertInto("auditLog")
    .values({
      actionType: "READ",
      entityType: "PACKET",
      entityId: params.packetId,
      userId: params.actorUserId,
      details: {
        packetDuplicatePolicy: "idempotent_reuse",
        ownerUserId: params.ownerUserId,
        packetType: params.packetType,
        selectedIssueIds: params.selectedIssueIds,
        creditorObligationTestId: params.linkedFindingId,
      } as any,
      status: "SUCCESS",
      timestamp: params.now,
      region: "CA",
    })
    .execute();
}

function readStoredExtractionGate(value: unknown): { packetReady: boolean | null; status: string | null } {
  const details = objectValue(value);
  const gate = objectValue(details?.extractionConfidenceGate);
  return {
    packetReady: typeof gate?.packetReady === "boolean" ? gate.packetReady : null,
    status: typeof gate?.status === "string" ? gate.status.toLowerCase() : null,
  };
}

function isNeedsManualReviewEvidence(evidenceReference: string | null | undefined): boolean {
  return !evidenceReference?.trim() || evidenceReference.trim().toLowerCase() === "needs manual review";
}

function readinessIssueFromRow(row: IssueRow, packetType: DisputePacketType = "credit_bureau"): PacketReadinessIssueInput {
  const details = parseDetails(row.issueTechnicalDetails);
  const disputedItemInput = buildConsumerDisputedItemInput(row, packetType);
  return {
    issueId: row.issueId,
    userId: row.userId,
    tradelineId: row.tradelineId,
    bureauId: row.bureauId,
    userStatus: row.issueUserStatus,
    validationStatus: row.issueValidationStatus,
    autoGenerated: row.issueAutoGenerated,
    technicalDetails: details,
    evidenceReference: disputedItemInput.evidenceReference ?? evidenceReferenceForRow(row, details),
    packetTypes: packetTypesForRow(row),
    packetNarrative: disputedItemInput.narrative ?? null,
  };
}

type PacketReadinessNarrativeFields = Pick<
  PacketReadinessBlocker,
  "disputeCategory" | "cautionLevel" | "issueSummary" | "readinessWarnings" | "readinessBlockers"
>;

function addBlocker(
  blockers: PacketReadinessBlocker[],
  code: PacketReadinessReasonCode,
  message: string,
  findingId?: number,
  narrativeFields: PacketReadinessNarrativeFields = {},
): void {
  blockers.push(
    findingId === undefined
      ? { code, message, ...narrativeFields }
      : { findingId, code, message, ...narrativeFields },
  );
}

function addWarning(
  warnings: PacketReadinessWarning[],
  code: PacketReadinessReasonCode,
  message: string,
  findingId?: number,
  narrativeFields: PacketReadinessNarrativeFields = {},
): void {
  warnings.push(
    findingId === undefined
      ? { code, message, ...narrativeFields }
      : { findingId, code, message, ...narrativeFields },
  );
}

function reasonCodesFor(
  blockers: PacketReadinessBlocker[],
  warnings: PacketReadinessWarning[],
): PacketReadinessReasonCode[] {
  return Array.from(new Set([...blockers.map((blocker) => blocker.code), ...warnings.map((warning) => warning.code)]));
}

export function evaluatePacketReadinessForIssues(
  user: Pick<User, "id" | "role">,
  input: DisputePacketBuildInput,
  issues: PacketReadinessIssueInput[],
): PacketReadinessResult {
  const selectedIssueIds = dedupeIssueIds(input.selectedIssueIds);
  const blockers: PacketReadinessBlocker[] = [];
  const warnings: PacketReadinessWarning[] = [];
  const blockedFindingIds = new Set<number>();
  const issueById = new Map(issues.map((issue) => [issue.issueId, issue]));
  const missingIssueIds = selectedIssueIds.filter((issueId) => !issueById.has(issueId));
  const selectedIssues = selectedIssueIds
    .map((issueId) => issueById.get(issueId))
    .filter((issue): issue is PacketReadinessIssueInput => Boolean(issue));

  if (selectedIssueIds.length === 0) {
    addBlocker(blockers, "NO_FINDINGS", "Select at least one report finding before creating a packet.");
  }

  for (const issueId of missingIssueIds) {
    blockedFindingIds.add(issueId);
    addBlocker(blockers, "FINDING_NOT_FOUND", `Finding #${issueId} was not found.`, issueId);
  }

  const ownerIds = Array.from(
    new Set(selectedIssues.map((issue) => issue.userId).filter((id): id is number => typeof id === "number")),
  );
  if (ownerIds.length > 1) {
    addBlocker(blockers, "MIXED_OWNER_SELECTION", "Select findings for one consumer at a time.");
  }

  if (user.role !== "admin") {
    for (const issue of selectedIssues) {
      if (issue.userId !== user.id) {
        blockedFindingIds.add(issue.issueId);
        addBlocker(blockers, "UNAUTHORIZED_FINDING", "You do not have access to this finding.", issue.issueId);
      }
    }
  }

  const tradelineIds = Array.from(
    new Set(selectedIssues.map((issue) => issue.tradelineId).filter((id): id is number => typeof id === "number")),
  );
  if (selectedIssues.length > 1 && tradelineIds.length > 1) {
    addBlocker(blockers, "MIXED_TRADELINE_SELECTION", "Create one packet per account/tradeline.");
  }

  if (input.packetType === "credit_bureau") {
    const bureauIds = Array.from(
      new Set(selectedIssues.map((issue) => issue.bureauId).filter((id): id is number => typeof id === "number")),
    );
    if (!input.recipientBureauId && bureauIds.length > 1) {
      addBlocker(blockers, "MIXED_BUREAU_SELECTION", "Select findings from one credit bureau at a time.");
    }
    if (input.recipientBureauId) {
      for (const issue of selectedIssues) {
        if (issue.bureauId && issue.bureauId !== input.recipientBureauId) {
          blockedFindingIds.add(issue.issueId);
          addBlocker(
            blockers,
            "RECIPIENT_BUREAU_MISMATCH",
            "This finding does not match the requested credit bureau.",
            issue.issueId,
          );
        }
      }
    }
  }

  if (input.packetType === "collection_agency") {
    for (const issue of selectedIssues) {
      if (!issue.packetTypes?.includes("collection_agency")) {
        blockedFindingIds.add(issue.issueId);
        addBlocker(
          blockers,
          "PACKET_TYPE_UNAVAILABLE",
          "This finding is not eligible for a collection agency packet.",
          issue.issueId,
        );
      }
    }
  }

  for (const issue of selectedIssues) {
    const userStatus = issue.userStatus?.toLowerCase() ?? "active";
    const validationStatus = issue.validationStatus?.toUpperCase() ?? null;
    const missingRequiredEvidence = isNeedsManualReviewEvidence(issue.evidenceReference);
    const confidenceGate = evaluateViolationPacketConfidenceGate({
      technicalDetails: issue.technicalDetails,
      validationStatus: issue.validationStatus,
      userStatus: issue.userStatus,
      autoGenerated: issue.autoGenerated,
    });
    const storedExtractionGate = readStoredExtractionGate(issue.technicalDetails);

    if (userStatus === "dismissed") {
      blockedFindingIds.add(issue.issueId);
      addBlocker(blockers, "DISMISSED_FINDING", "Dismissed findings cannot be used to create packets.", issue.issueId);
    }

    if (confidenceGate.blockerCode === "parser_uncertain" || validationStatus === "PARSER_UNCERTAIN") {
      blockedFindingIds.add(issue.issueId);
      addBlocker(
        blockers,
        "PARSER_UNCERTAIN",
        "Parser-uncertain findings need parser review before packet creation.",
        issue.issueId,
      );
    } else if (confidenceGate.blockerCode === "violation_needs_review" || validationStatus === "NEEDS_USER_REVIEW") {
      if (!confidenceGate.packetReady || userStatus !== "verified") {
        blockedFindingIds.add(issue.issueId);
        if (!missingRequiredEvidence) {
          addBlocker(
            blockers,
            "NEEDS_USER_REVIEW",
            "This finding must be verified before packet creation.",
            issue.issueId,
          );
        }
      }
    }

    const verifiedUserReview =
      userStatus === "verified" &&
      (validationStatus === "NEEDS_USER_REVIEW" || storedExtractionGate.status === "needs_user_review");
    if (
      storedExtractionGate.packetReady === false &&
      confidenceGate.blockerCode === null &&
      !verifiedUserReview
    ) {
      blockedFindingIds.add(issue.issueId);
      addBlocker(
        blockers,
        "EXTRACTION_CONFIDENCE_NOT_READY",
        "The source report extraction is not packet-ready for this finding.",
        issue.issueId,
      );
    }

    if (missingRequiredEvidence) {
      blockedFindingIds.add(issue.issueId);
      addBlocker(
        blockers,
        "MISSING_REQUIRED_EVIDENCE",
        "Required source-report evidence is missing for this finding.",
        issue.issueId,
      );
      addBlocker(
        blockers,
        "MANUAL_REVIEW_REQUIRED",
        "This finding is marked Needs manual review.",
        issue.issueId,
      );
    }

    if (issue.packetNarrative) {
      const narrativeReadiness = evaluatePacketNarrativeReadiness(issue.packetNarrative, {
        evidenceExpected: true,
      });
      const narrativeFields: PacketReadinessNarrativeFields = {
        disputeCategory: narrativeReadiness.disputeCategory,
        cautionLevel: narrativeReadiness.cautionLevel,
        issueSummary: narrativeReadiness.issueSummary,
        readinessWarnings: narrativeReadiness.readinessWarnings,
        readinessBlockers: narrativeReadiness.readinessBlockers,
      };

      if (narrativeReadiness.readinessBlockers.length > 0) {
        blockedFindingIds.add(issue.issueId);
        addBlocker(
          blockers,
          "WEAK_PACKET_NARRATIVE",
          narrativeReadiness.readinessBlockers[0],
          issue.issueId,
          narrativeFields,
        );
      }

      for (const warning of narrativeReadiness.readinessWarnings) {
        addWarning(warnings, "WEAK_PACKET_NARRATIVE", warning, issue.issueId, narrativeFields);
      }
    }
  }

  const eligibleFindingIds = selectedIssues
    .filter((issue) => !blockedFindingIds.has(issue.issueId))
    .map((issue) => issue.issueId);
  const ineligibleFindingIds = Array.from(new Set([...missingIssueIds, ...blockedFindingIds]));
  const reasonCodes = reasonCodesFor(blockers, warnings);

  return {
    packetReady: blockers.length === 0 && eligibleFindingIds.length === selectedIssueIds.length && selectedIssueIds.length > 0,
    blockers,
    warnings,
    eligibleFindingIds,
    ineligibleFindingIds,
    reasonCodes,
  };
}

export function assertPacketReadiness(readiness: PacketReadinessResult): void {
  if (readiness.packetReady) return;
  const firstBlocker = readiness.blockers[0];
  const statusCode = readiness.reasonCodes.includes("UNAUTHORIZED_FINDING")
    ? 403
    : readiness.reasonCodes.includes("FINDING_NOT_FOUND")
      ? 404
      : 400;
  throw new BusinessRuleError(
    firstBlocker?.message ?? "Packet readiness requirements are not satisfied.",
    statusCode,
  );
}

export function resolvePacketCreditorObligationTestId(selectedIssueIds: number[]): number | null {
  const uniqueIds = dedupeIssueIds(selectedIssueIds);
  return uniqueIds.length === 1 ? uniqueIds[0] : null;
}

function candidateFromRow(row: IssueRow, packetType: DisputePacketType = "credit_bureau"): DisputePacketCandidate {
  const details = parseDetails(row.issueTechnicalDetails);
  const evidenceReference = evidenceReferenceForRow(row, details);
  const creditorCollectorName =
    packetType === "collection_agency"
      ? firstKnownText([row.collectionAgencyName, row.creditorName, row.originalCreditorName]) ?? "Collection agency"
      : firstKnownText([row.creditorName, row.originalCreditorName, row.collectionAgencyName]) ?? "Company listed on report";

  return {
    issueId: row.issueId,
    tradelineId: row.tradelineId,
    userId: Number(row.userId),
    userEmail: row.userEmail,
    userDisplayName: row.userDisplayName,
    packetTypes: packetTypesForRow(row),
    bureauName: row.bureauName,
    creditorCollectorName: redactSensitiveText(creditorCollectorName),
    collectionAgencyName: row.collectionAgencyName ? redactSensitiveText(row.collectionAgencyName) : null,
    maskedAccountNumber: maskAccountNumber(row.accountNumber),
    issueType: labelizeIssueType(issueTypeForRow(row)),
    explanation: redactSensitiveText(
      sanitizeComplianceNeutralText(row.issueUserExplanation ?? row.issueRecommendedAction) ??
        "Review this account information against the source report.",
      row.accountNumber,
    ),
    evidenceReference,
    requestedAction: actionForIssue(issueTypeForRow(row), packetType),
    needsManualReview: evidenceReference === "Needs manual review",
    reportDate: toPacketDate(row.reportDate),
  };
}

function consumerDisputeReasonForRow(row: PacketConsumerDisputedItemSource, packetType: DisputePacketType): string {
  const findingReason = sanitizeComplianceNeutralText(row.issueUserExplanation);
  if (findingReason) return redactSensitiveText(findingReason, row.accountNumber);

  const recommendedAction = sanitizeComplianceNeutralText(row.issueRecommendedAction);
  if (recommendedAction) return redactSensitiveText(recommendedAction, row.accountNumber);

  const accountName =
    packetType === "collection_agency"
      ? firstKnownText([row.collectionAgencyName, row.creditorName, row.originalCreditorName]) ?? "this collection account"
      : firstKnownText([row.creditorName, row.originalCreditorName, row.collectionAgencyName]) ?? "this account";
  const issueLabel = labelizeIssueType(issueTypeForRow(row)).toLowerCase();

  if (packetType === "collection_agency") {
    return `I dispute the ${issueLabel} for ${redactSensitiveText(accountName, row.accountNumber)} and am asking you to verify whether this collection account information is accurate, complete, and supported by records showing the authority to collect or report this account.`;
  }

  return `I dispute the ${issueLabel} for ${redactSensitiveText(accountName, row.accountNumber)} and am asking you to verify whether this information is accurate, complete, and supported by the records used to report this account.`;
}

export function buildConsumerDisputedItemInput(
  row: PacketConsumerDisputedItemSource,
  packetType: DisputePacketType,
): SimpleDisputedItemInput {
  const details = parseDetails(row.issueTechnicalDetails);
  const evidence = objectValue(details.evidenceLink) ?? objectValue(objectValue(details.deterministicRule)?.evidence);
  const fieldName = fieldFromDetails(details);
  const displayFieldName = formatPacketFieldLabel(fieldName ?? "Account information");
  const reportedValue =
    firstText(details, ["reportedValue", "actualValue", "detectedValue", "currentValue", "reportedAs"]) ??
    valueFromTradeline(row, fieldName) as string | number | Date | null;
  const expectedValue =
    firstText(details, ["expectedValue", "correctedValue", "expected", "shouldBe", "basisValue"]) ??
    "Not known";
  const creditorName = firstKnownText([row.creditorName, row.originalCreditorName, row.collectionAgencyName]);
  const collectionName = firstKnownText([row.collectionAgencyName, row.creditorName, row.originalCreditorName]);
  const issueType = issueTypeForRow(row);
  const evidenceReference = evidenceReferenceForRow(row, details);
  const findingReason = consumerDisputeReasonForRow(row, packetType);
  const pageNumber = Number(evidence?.pageNumber ?? evidence?.page ?? details.pageNumber ?? details.page);
  const evidenceSnippet = firstKnownText([
    evidence ? firstText(evidence, ["textSnippet", "excerpt"]) : null,
    firstText(details, ["textSnippet", "evidenceSnippet", "excerpt"]),
  ]);
  const ruleRecords = internalRuleRecords(details);
  const narrative = buildPacketNarrative({
    packetType,
    issueId: row.issueId,
    tradelineId: row.tradelineId,
    reportArtifactId: row.reportArtifactId,
    reportType: packetType === "collection_agency"
      ? "Collection agency account information"
      : row.bureauName
        ? `${row.bureauName} credit report`
        : "credit report",
    reportDate: row.reportDate ?? null,
    bureauName: row.bureauName ?? null,
    consumerProvince: row.consumerProvince ?? null,
    accountName: packetType === "collection_agency" ? collectionName : creditorName,
    accountNumber: row.accountNumber,
    accountType: row.accountType ?? null,
    accountStatus: row.status,
    balance: row.balance,
    currentBalance: row.currentBalance,
    openedDate: row.openedDate,
    closedDate: row.dateClosed,
    dateOfFirstDelinquency: row.dateOfFirstDelinquency,
    dateOfLastPayment: row.dateOfLastPayment,
    lastActivityDate: row.lastActivityDate,
    dateLastReported: row.lastReportedDate,
    amountPastDue: row.amountPastDue,
    isCollectionAccount: row.isCollectionAccount ?? null,
    collectionAgencyName: row.collectionAgencyName,
    originalCreditorName: row.originalCreditorName,
    disputedField: displayFieldName,
    reportedValue,
    expectedValue,
    issueType,
    evidenceReference,
    evidencePageNumber: Number.isFinite(pageNumber) && pageNumber > 0 ? pageNumber : null,
    evidenceSnippet,
    ruleIds: collectStringValues(ruleRecords, ["ruleId", "ruleIds", "deterministicRuleId", "runtimeRuleId"]),
    regulationIds: collectStringValues(ruleRecords, [
      "regulationId",
      "regulationIds",
      "referenceId",
      "referenceIds",
      "legalReferenceId",
      "legalReferenceIds",
      "authorityId",
      "authorityIds",
    ]),
    evidenceIds: evidenceIdsFromDetails(details),
  });

  return {
    issueId: row.issueId,
    tradelineId: row.tradelineId,
    creditorCollectorName: packetType === "collection_agency" ? collectionName : creditorName,
    sourceFurnisherName: packetType === "credit_bureau" ? firstKnownText([row.creditorName, row.originalCreditorName]) : row.originalCreditorName,
    accountNumber: row.accountNumber,
    disputedField: displayFieldName,
    reportedValue: formatPacketDisplayValue(fieldName ?? displayFieldName, reportedValue, row.accountNumber),
    expectedValue: formatPacketExpectedValue(fieldName ?? displayFieldName, expectedValue, row.accountNumber),
    issueType,
    explanation: findingReason,
    findingReason,
    findingRecommendedAction: row.issueRecommendedAction,
    evidenceReference,
    requestedAction: actionForIssue(issueType, packetType),
    narrative,
  };
}

function toDisputedItemInput(row: IssueRow, packetType: DisputePacketType): SimpleDisputedItemInput {
  return buildConsumerDisputedItemInput(row, packetType);
}

function addressLinesFromRecipient(recipient: RecipientRecord): string[] {
  if (recipient.addressLines.length > 0) return recipient.addressLines;
  const lines = [
    recipient.addressLine1,
    recipient.addressLine2,
    recipient.city && recipient.province && recipient.postalCode
      ? `${recipient.city}, ${recipient.province} ${recipient.postalCode}`
      : null,
  ];
  return lines.filter((line): line is string => Boolean(line));
}

function recipientFromInput(input: DisputePacketRecipientInput | undefined, fallbackName: string): RecipientRecord {
  const name = input?.name?.trim() || fallbackName;
  const addressLines = [
    input?.addressLine1 ?? null,
    input?.addressLine2 ?? null,
    input?.city && input?.province && input?.postalCode
      ? `${input.city}, ${input.province} ${input.postalCode}`
      : null,
  ].filter((line): line is string => Boolean(line));

  return {
    name,
    addressLine1: input?.addressLine1?.trim() || null,
    addressLine2: input?.addressLine2?.trim() || null,
    city: input?.city?.trim() || null,
    province: input?.province?.trim() || null,
    postalCode: input?.postalCode?.trim() || null,
    addressLines,
  };
}

function resolveBureauRecipient(row: IssueRow, input?: DisputePacketRecipientInput): RecipientRecord {
  if (input?.name || input?.addressLine1) {
    return recipientFromInput(input, row.bureauName || "Credit Bureau");
  }

  const hardcoded = row.bureauName ? getBureauDisputeAddress(row.bureauName) : null;
  if (hardcoded) {
    return {
      name: hardcoded.bureauName,
      addressLine1: hardcoded.addressLine1,
      addressLine2: hardcoded.department,
      city: hardcoded.city,
      province: hardcoded.province,
      postalCode: hardcoded.postalCode,
      addressLines: [
        hardcoded.department,
        hardcoded.addressLine1,
        `${hardcoded.city}, ${hardcoded.province} ${hardcoded.postalCode}`,
      ],
    };
  }

  return {
    name: row.bureauName || "Credit Bureau",
    addressLine1: row.bureauAddressLine1,
    addressLine2: row.bureauAddressLine2,
    city: row.bureauCity,
    province: row.bureauProvince,
    postalCode: row.bureauPostalCode,
    addressLines: [
      row.bureauAddressLine1,
      row.bureauAddressLine2,
      row.bureauCity && row.bureauProvince && row.bureauPostalCode
        ? `${row.bureauCity}, ${row.bureauProvince} ${row.bureauPostalCode}`
        : null,
    ].filter((line): line is string => Boolean(line)),
  };
}

function resolveCollectionRecipient(rows: IssueRow[], input?: DisputePacketRecipientInput): RecipientRecord {
  const collectionNames = Array.from(
    new Set(rows.map((row) => row.collectionAgencyName?.trim()).filter((name): name is string => Boolean(name)))
  );

  if (!input?.name && collectionNames.length > 1) {
    throw new BusinessRuleError("Select collection items for one collection agency at a time.");
  }

  const fallbackName = collectionNames[0] ?? "Collection agency";
  if (!input?.name && fallbackName === "Collection agency") {
    throw new BusinessRuleError("A collection agency name is required for a collection agency packet.");
  }

  return recipientFromInput(input, fallbackName);
}

function buildConsumer(row: IssueRow) {
  const cityLine =
    row.consumerCity && row.consumerProvince && row.consumerPostalCode
      ? `${row.consumerCity}, ${row.consumerProvince} ${row.consumerPostalCode}`
      : null;

  return {
    name: firstKnownText([row.consumerFullName, row.userDisplayName]) ?? "Consumer",
    address: [row.consumerAddressLine1, row.consumerAddressLine2, cityLine].filter((line): line is string => Boolean(line)),
    phone: row.consumerPhone,
    email: row.consumerEmail ?? row.userEmail,
  };
}

function assertRowsCanBuild(user: User, rows: IssueRow[], input: DisputePacketBuildInput): void {
  if (rows.length === 0) {
    throw new BusinessRuleError("No disputed items were found.", 404);
  }

  const missingIds = input.selectedIssueIds.filter((id) => !rows.some((row) => row.issueId === id));
  if (missingIds.length > 0) {
    throw new BusinessRuleError(`Disputed item not found: ${missingIds[0]}`, 404);
  }

  const ownerIds = Array.from(new Set(rows.map((row) => row.userId).filter((id): id is number => typeof id === "number")));
  if (ownerIds.length !== 1) {
    throw new BusinessRuleError("Select disputed items for one consumer at a time.");
  }

  if (user.role !== "admin" && ownerIds[0] !== user.id) {
    throw new BusinessRuleError("Unauthorized access to disputed items.", 403);
  }

  const tradelineIds = Array.from(new Set(rows.map((row) => row.tradelineId)));
  if (rows.length > 1 && tradelineIds.length > 1) {
    throw new BusinessRuleError("Create one packet per account/tradeline.");
  }

  if (input.packetType === "credit_bureau") {
    const bureauIds = Array.from(new Set(rows.map((row) => row.bureauId).filter((id): id is number => typeof id === "number")));
    if (!input.recipientBureauId && bureauIds.length > 1) {
      throw new BusinessRuleError("Select disputed items from one credit bureau at a time.");
    }
    if (input.recipientBureauId && rows.some((row) => row.bureauId && row.bureauId !== input.recipientBureauId)) {
      throw new BusinessRuleError("Selected items do not match the requested credit bureau.");
    }
  }

  if (input.packetType === "collection_agency" && rows.some((row) => !packetTypesForRow(row).includes("collection_agency"))) {
    throw new BusinessRuleError("One or more selected items is not available for a collection agency packet.");
  }
}

async function getIssueRows(issueIds: number[]): Promise<IssueRow[]> {
  return db
    .selectFrom("creditorObligationTest as issue")
    .innerJoin("tradeline as tradeline", "tradeline.id", "issue.tradelineId")
    .leftJoin("users as users", "users.id", "tradeline.userId")
    .leftJoin("userAccount as userAccount", "userAccount.userId", "tradeline.userId")
    .leftJoin("bureau as bureau", "bureau.id", "tradeline.bureauId")
    .leftJoin("creditor as creditor", "creditor.id", "tradeline.creditorId")
    .leftJoin("reportArtifact as reportArtifact", "reportArtifact.id", "tradeline.reportArtifactId")
    .select([
      "issue.id as issueId",
      "issue.userExplanation as issueUserExplanation",
      "issue.recommendedAction as issueRecommendedAction",
      "issue.violationCategory as issueViolationCategory",
      "issue.disputeVector as issueDisputeVector",
      "issue.technicalDetails as issueTechnicalDetails",
      "issue.userStatus as issueUserStatus",
      "issue.validationStatus as issueValidationStatus",
      "issue.autoGenerated as issueAutoGenerated",
      "tradeline.id as tradelineId",
      "tradeline.userId as userId",
      "users.email as userEmail",
      "users.displayName as userDisplayName",
      "userAccount.fullName as consumerFullName",
      "userAccount.email as consumerEmail",
      "userAccount.addressLine1 as consumerAddressLine1",
      "userAccount.addressLine2 as consumerAddressLine2",
      "userAccount.city as consumerCity",
      "userAccount.province as consumerProvince",
      "userAccount.postalCode as consumerPostalCode",
      "userAccount.phone as consumerPhone",
      "bureau.id as bureauId",
      "bureau.name as bureauName",
      "bureau.addressLine1 as bureauAddressLine1",
      "bureau.addressLine2 as bureauAddressLine2",
      "bureau.city as bureauCity",
      "bureau.province as bureauProvince",
      "bureau.postalCode as bureauPostalCode",
      "creditor.name as creditorName",
      "tradeline.accountNumber as accountNumber",
      "tradeline.accountType as accountType",
      "tradeline.status as status",
      "tradeline.balance as balance",
      "tradeline.currentBalance as currentBalance",
      "tradeline.creditLimit as creditLimit",
      "tradeline.highCredit as highCredit",
      "tradeline.amountPastDue as amountPastDue",
      "tradeline.openedDate as openedDate",
      "tradeline.dateClosed as dateClosed",
      "tradeline.dateOfFirstDelinquency as dateOfFirstDelinquency",
      "tradeline.dateOfLastPayment as dateOfLastPayment",
      "tradeline.lastActivityDate as lastActivityDate",
      "tradeline.lastReportedDate as lastReportedDate",
      "tradeline.collectionAgencyName as collectionAgencyName",
      "tradeline.originalCreditorName as originalCreditorName",
      "tradeline.isCollectionAccount as isCollectionAccount",
      "tradeline.reportArtifactId as reportArtifactId",
      "reportArtifact.data as reportArtifactData",
      "reportArtifact.reportDate as reportDate",
      "tradeline.sourceText as sourceText",
    ])
    .where("issue.id", "in", issueIds)
    .execute() as Promise<IssueRow[]>;
}

export async function getDisputePacketCandidates(
  user: User,
  input: { packetType?: DisputePacketType; limit?: number } = {},
): Promise<DisputePacketCandidate[]> {
  const limit = Math.min(Math.max(input.limit ?? 50, 1), 100);
  let query = db
    .selectFrom("creditorObligationTest as issue")
    .innerJoin("tradeline as tradeline", "tradeline.id", "issue.tradelineId")
    .leftJoin("users as users", "users.id", "tradeline.userId")
    .leftJoin("userAccount as userAccount", "userAccount.userId", "tradeline.userId")
    .leftJoin("bureau as bureau", "bureau.id", "tradeline.bureauId")
    .leftJoin("creditor as creditor", "creditor.id", "tradeline.creditorId")
    .leftJoin("reportArtifact as reportArtifact", "reportArtifact.id", "tradeline.reportArtifactId")
    .select([
      "issue.id as issueId",
      "issue.userExplanation as issueUserExplanation",
      "issue.recommendedAction as issueRecommendedAction",
      "issue.violationCategory as issueViolationCategory",
      "issue.disputeVector as issueDisputeVector",
      "issue.technicalDetails as issueTechnicalDetails",
      "issue.userStatus as issueUserStatus",
      "issue.validationStatus as issueValidationStatus",
      "issue.autoGenerated as issueAutoGenerated",
      "tradeline.id as tradelineId",
      "tradeline.userId as userId",
      "users.email as userEmail",
      "users.displayName as userDisplayName",
      "userAccount.fullName as consumerFullName",
      "userAccount.email as consumerEmail",
      "userAccount.addressLine1 as consumerAddressLine1",
      "userAccount.addressLine2 as consumerAddressLine2",
      "userAccount.city as consumerCity",
      "userAccount.province as consumerProvince",
      "userAccount.postalCode as consumerPostalCode",
      "userAccount.phone as consumerPhone",
      "bureau.id as bureauId",
      "bureau.name as bureauName",
      "bureau.addressLine1 as bureauAddressLine1",
      "bureau.addressLine2 as bureauAddressLine2",
      "bureau.city as bureauCity",
      "bureau.province as bureauProvince",
      "bureau.postalCode as bureauPostalCode",
      "creditor.name as creditorName",
      "tradeline.accountNumber as accountNumber",
      "tradeline.accountType as accountType",
      "tradeline.status as status",
      "tradeline.balance as balance",
      "tradeline.currentBalance as currentBalance",
      "tradeline.creditLimit as creditLimit",
      "tradeline.highCredit as highCredit",
      "tradeline.amountPastDue as amountPastDue",
      "tradeline.openedDate as openedDate",
      "tradeline.dateClosed as dateClosed",
      "tradeline.dateOfFirstDelinquency as dateOfFirstDelinquency",
      "tradeline.dateOfLastPayment as dateOfLastPayment",
      "tradeline.lastActivityDate as lastActivityDate",
      "tradeline.lastReportedDate as lastReportedDate",
      "tradeline.collectionAgencyName as collectionAgencyName",
      "tradeline.originalCreditorName as originalCreditorName",
      "tradeline.isCollectionAccount as isCollectionAccount",
      "tradeline.reportArtifactId as reportArtifactId",
      "reportArtifact.data as reportArtifactData",
      "reportArtifact.reportDate as reportDate",
      "tradeline.sourceText as sourceText",
    ])
    .where("issue.userStatus", "!=", "dismissed")
    .orderBy("issue.detectedAt", "desc")
    .orderBy("issue.id", "desc")
    .limit(limit);

  if (user.role !== "admin") {
    query = query.where("tradeline.userId", "=", user.id);
  }

  const rows = await query.execute() as IssueRow[];
  return rows
    .filter((row) => {
      const packetType = input.packetType ?? "credit_bureau";
      const readiness = evaluatePacketReadinessForIssues(
        user,
        { packetType, selectedIssueIds: [row.issueId] },
        [readinessIssueFromRow(row, packetType)],
      );
      return readiness.packetReady;
    })
    .map((row) => candidateFromRow(row, input.packetType ?? "credit_bureau"))
    .filter((candidate) => !input.packetType || candidate.packetTypes.includes(input.packetType));
}

export async function validateDisputePacketReadiness(
  user: User,
  input: DisputePacketBuildInput,
): Promise<PacketReadinessResult> {
  const selectedIssueIds = dedupeIssueIds(input.selectedIssueIds);
  const rows = await getIssueRows(selectedIssueIds);

  if (user.role !== "admin" && rows.some((row) => row.userId !== user.id)) {
    throw new BusinessRuleError("Unauthorized access to disputed items.", 403);
  }

  return evaluatePacketReadinessForIssues(
    user,
    { ...input, selectedIssueIds },
    rows.map((row) => readinessIssueFromRow(row, input.packetType)),
  );
}

export async function buildDisputePacketPreview(
  user: User,
  input: DisputePacketBuildInput,
): Promise<DisputePacketPreview> {
  const uniqueIssueIds = dedupeIssueIds(input.selectedIssueIds);
  const rows = await getIssueRows(uniqueIssueIds);
  assertRowsCanBuild(user, rows, { ...input, selectedIssueIds: uniqueIssueIds });
  const readiness = evaluatePacketReadinessForIssues(
    user,
    { ...input, selectedIssueIds: uniqueIssueIds },
    rows.map((row) => readinessIssueFromRow(row, input.packetType)),
  );
  assertPacketReadiness(readiness);

  const firstRow = rows[0];
  const ownerUserId = Number(firstRow.userId);
  const recipientRecord =
    input.packetType === "collection_agency"
      ? resolveCollectionRecipient(rows, input.recipient)
      : resolveBureauRecipient(firstRow, input.recipient);
  const reportDate = rows.find((row) => row.reportDate)?.reportDate ?? null;
  const reportType =
    input.packetType === "collection_agency"
      ? "Collection agency account information"
      : `${firstRow.bureauName || "Credit Bureau"} credit report`;

  const packet = attachEvidenceLocationsToPacket(attachInternalPacketMetadata(buildSimpleDisputePacketContent({
    packetType: input.packetType,
    reportType,
    reportDate,
    recipient: {
      type: input.packetType,
      name: recipientRecord.name,
      address: addressLinesFromRecipient(recipientRecord),
    },
    consumer: buildConsumer(firstRow),
    disputedItems: rows.map((row) => toDisputedItemInput(row, input.packetType)),
    reportArtifactIds: rows.map((row) => row.reportArtifactId),
    generatedByUserId: user.id,
  }), rows, readiness), rows);

  return {
    packet,
    recipientRecord,
    ownerUserId,
    firstTradelineId: firstRow.tradelineId,
    bureauId: input.packetType === "credit_bureau" ? (input.recipientBureauId ?? firstRow.bureauId) : null,
    selectedIssueIds: uniqueIssueIds,
    linkedFindingId: resolvePacketCreditorObligationTestId(uniqueIssueIds),
    issueRows: rows,
    readiness,
  };
}

export async function createDisputePacketRecord(
  user: User,
  input: DisputePacketBuildInput,
): Promise<DisputePacketCreateResult> {
  const preview = await buildDisputePacketPreview(user, input);
  const now = new Date();
  const packetType = packetPersistenceType(input);
  assertPacketFindingRowsCanBeWritten(user, preview);
  await ensureDisputePacketFindingsSchema();

  const result = await db.transaction().execute(async (trx) => {
    const [lockKey1, lockKey2] = packetIdempotencyLockParts(preview, packetType);
    await sql`select pg_advisory_xact_lock(${lockKey1}, ${lockKey2})`.execute(trx);

    const existing = await findIdempotentExistingPacket(trx, preview, packetType);
    if (existing) {
      await writePacketIdempotentReuseAudit(trx, {
        packetId: existing.id,
        actorUserId: user.id,
        ownerUserId: preview.ownerUserId,
        packetType,
        selectedIssueIds: preview.packet.metadata.selectedIssueIds,
        linkedFindingId: preview.linkedFindingId,
        now,
      });

      return {
        packetId: existing.id,
        packet: existing.content,
        status: existing.status ?? "generated",
        duplicatePolicy: "idempotent_reuse" as const,
        reusedExistingPacket: true,
        existingPacketId: existing.id,
      };
    }

    const packet = await trx
      .insertInto("packet")
      .values({
        userId: preview.ownerUserId,
        tradelineId: preview.firstTradelineId,
        bureauId: preview.bureauId,
        creditorObligationTestId: preview.linkedFindingId,
        type: packetType,
        status: "generated",
        processingStatus: "completed",
        content: JSON.stringify(preview.packet),
        terminalLabel: null,
        letterDate: now,
        recipientName: preview.recipientRecord.name,
        recipientAddressLine1: preview.recipientRecord.addressLine1,
        recipientAddressLine2: preview.recipientRecord.addressLine2,
        recipientCity: preview.recipientRecord.city,
        recipientProvince: preview.recipientRecord.province,
        recipientPostalCode: preview.recipientRecord.postalCode,
        region: "CA",
      })
      .returning(["id", "status"])
      .executeTakeFirstOrThrow();

    await trx
      .insertInto("disputePacketFindings")
      .values(buildDisputePacketFindingRows(preview, packet.id, packet.status ?? "generated", user.id, now))
      .execute();

    await appendEvidenceEvent({
      packetId: packet.id,
      eventType: "PACKET_GENERATED",
      description: `${preview.packet.title} generated from selected report issue(s).`,
      organizationId: user.organizationId,
      region: "CA",
      at: now,
    }, trx);

    await trx
      .insertInto("auditLog")
      .values({
        actionType: "PACKET_GENERATED",
        entityType: "PACKET",
        entityId: packet.id,
        userId: user.id,
        details: {
          packetType,
          ownerUserId: preview.ownerUserId,
          selectedIssueIds: preview.packet.metadata.selectedIssueIds,
          creditorObligationTestId: preview.linkedFindingId,
        } as any,
        status: "SUCCESS",
        timestamp: now,
        region: "CA",
      })
      .execute();

    return {
      packetId: packet.id,
      packet: preview.packet,
      status: packet.status ?? "generated",
      duplicatePolicy: "created_new" as const,
      reusedExistingPacket: false,
    };
  });

  return result;
}
