import {
  classifyViolationEvidenceQuality,
  evaluateViolationPacketConfidenceGate,
  type ParserConfidenceGateStatus,
  type ViolationEvidenceQualityStatus,
  type ViolationPacketGateBlockerCode,
} from "./violationPacketConfidenceGate";

export type FindingReadinessInput = {
  technicalDetails?: unknown;
  validationStatus?: string | null;
  userStatus?: string | null;
  autoGenerated?: boolean | null;
};

export type FindingPacketReadinessSummary = {
  packetReady: boolean;
  packetReadinessStatus: ParserConfidenceGateStatus;
  packetReadinessMessage: string;
  packetReadinessBlockerCode: ViolationPacketGateBlockerCode | null;
  evidenceQualityStatus: ViolationEvidenceQualityStatus;
  blockerReasonCodes: string[];
};

const DEFAULT_BLOCKED_REASON = "PACKET_READINESS_BLOCKED";

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function stringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is string => typeof item === "string" && item.trim().length > 0);
}

function storedPacketEligibilityReasonCodes(technicalDetails: unknown): string[] {
  const details = isRecord(technicalDetails) ? technicalDetails : {};
  const defensibility = isRecord(details.defensibility) ? details.defensibility : {};
  const packetEligibility = isRecord(defensibility.packetEligibility)
    ? defensibility.packetEligibility
    : {};

  return stringArray(packetEligibility.reasonCodes);
}

export function summarizeFindingPacketReadiness(
  input: FindingReadinessInput,
): FindingPacketReadinessSummary {
  const gate = evaluateViolationPacketConfidenceGate({
    technicalDetails: input.technicalDetails,
    validationStatus: input.validationStatus,
    userStatus: input.userStatus,
    autoGenerated: input.autoGenerated,
  });
  const evidenceQuality = classifyViolationEvidenceQuality({
    technicalDetails: input.technicalDetails,
    validationStatus: input.validationStatus,
  });
  const packetReady = gate.packetReady && evidenceQuality.status === "strong";
  const reasonCodes = [
    ...storedPacketEligibilityReasonCodes(input.technicalDetails),
    ...evidenceQuality.reasonCodes,
    ...(gate.blockerCode === "parser_uncertain" ? ["PARSER_UNCERTAIN"] : []),
    ...(gate.blockerCode === "violation_needs_review" ? ["NEEDS_USER_REVIEW"] : []),
  ];
  const uniqueReasonCodes = Array.from(new Set(reasonCodes));

  return {
    packetReady,
    packetReadinessStatus: gate.status,
    packetReadinessMessage: gate.message,
    packetReadinessBlockerCode: gate.blockerCode,
    evidenceQualityStatus: evidenceQuality.status,
    blockerReasonCodes:
      packetReady || uniqueReasonCodes.length > 0
        ? uniqueReasonCodes
        : [DEFAULT_BLOCKED_REASON],
  };
}

const BLOCKER_REASON_COPY: Record<string, string> = {
  DISMISSED_FINDING: "Dismissed by user",
  EXTRACTION_CONFIDENCE_NOT_READY: "Report extraction needs review",
  MANUAL_REVIEW_REQUIRED: "Manual review required",
  MISSING_REQUIRED_EVIDENCE: "Source evidence is missing",
  NEEDS_USER_REVIEW: "Needs verification before a letter",
  PARSER_UNCERTAIN: "Source report text needs review",
  PARTIAL_EVIDENCE_METADATA: "Source evidence needs review",
  PACKET_READINESS_BLOCKED: "Review required before a letter",
};

export function formatFindingBlockerReason(code: string): string {
  return BLOCKER_REASON_COPY[code] ?? "Review required before a letter";
}

export function formatFindingBlockerReasons(codes: string[] | null | undefined): string[] {
  const labels = Array.from(
    new Set((codes ?? []).map((code) => formatFindingBlockerReason(code))),
  );
  return labels.length > 0 ? labels : [BLOCKER_REASON_COPY.PACKET_READINESS_BLOCKED];
}
