import type { LetterContent } from "./pdfGenerator";



/**
 * A backend-only helper that uses OpenAI to rewrite the narrative sections 
 * of a credit dispute letter so it sounds like a real person wrote it.
 *
 * @param letterContent The structured letter content generated by templates.
 * @returns A promise resolving to the humanized LetterContent, or the original on failure.
 */
export async function letterHumanizer(
  letterContent: LetterContent
): Promise<LetterContent> {
  try {
    // 1. Extract the narrative sections that need humanizing
    const sectionsToHumanize: Record<string, string> = {};

    if (letterContent.introduction) sectionsToHumanize.introduction = letterContent.introduction;
    if (letterContent.disputedItems) sectionsToHumanize.disputedItems = letterContent.disputedItems;
    if (letterContent.statutoryGrounds) sectionsToHumanize.statutoryGrounds = letterContent.statutoryGrounds;
    if (letterContent.requestedAction) sectionsToHumanize.requestedAction = letterContent.requestedAction;
    if (letterContent.statutoryTimeframe) sectionsToHumanize.statutoryTimeframe = letterContent.statutoryTimeframe;
    if (letterContent.certification) sectionsToHumanize.certification = letterContent.certification;

    // If there's nothing to humanize, just return the original
    if (Object.keys(sectionsToHumanize).length === 0) {
      return letterContent;
    }

    // 2. Define the system prompt
    const systemPrompt = `You are a helpful assistant that rewrites credit dispute letters to sound like a real Canadian consumer wrote them by hand, rather than a template engine.

Rules:
1. Rewrite the text as if a real Canadian consumer wrote it by hand.
2. Vary sentence length, structure, and vocabulary naturally.
3. Use first-person voice (e.g., "I noticed...", "When I checked my report...").
4. Keep ALL factual data exactly intact (dates, dollar amounts, account numbers, statute names/sections, bureau names).
5. Reference legislation naturally within sentences instead of using formal "Statutory Basis:" labels.
6. Keep a firm but polite tone — the consumer is asserting their rights, not being aggressive.
7. Avoid overly formal legalese — a normal person wouldn't write "I am formally disputing the accuracy and completeness of personal information".
8. Do NOT add any new facts, claims, or context not present in the original text.
9. If any value looks like an internal system code, character count, technical metric, or database ID rather than actual account data (e.g. '28 chars', 'Max 24 chars', 'Non-zero rating'), rephrase it naturally using the surrounding context or omit it entirely.
10. Output a JSON object containing the EXACT SAME keys as the input object, with the rewritten text as the values.`;

    // 3. Call OpenAI API
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      signal: AbortSignal.timeout(30000),
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: "gpt-5-mini",
        reasoning_effort: "low",
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: JSON.stringify(sectionsToHumanize) },
        ],
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI API returned status: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();
    
    // 4. Parse the AI response and merge it back
    const rewrittenTextRaw = data.choices?.[0]?.message?.content;
    if (!rewrittenTextRaw) {
      throw new Error("No content returned from OpenAI");
    }

    const rewrittenSections = JSON.parse(rewrittenTextRaw) as Record<string, string>;

    const mergedContent = {
      ...letterContent,
      introduction: rewrittenSections.introduction ?? letterContent.introduction,
      disputedItems: rewrittenSections.disputedItems ?? letterContent.disputedItems,
      statutoryGrounds: rewrittenSections.statutoryGrounds ?? letterContent.statutoryGrounds,
      requestedAction: rewrittenSections.requestedAction ?? letterContent.requestedAction,
      statutoryTimeframe: rewrittenSections.statutoryTimeframe ?? letterContent.statutoryTimeframe,
      certification: rewrittenSections.certification ?? letterContent.certification,
    };

        return mergedContent;
  } catch (error) {
    // 5. Fallback on any error
    console.error("Failed to humanize letter content. Falling back to original template.", error instanceof Error ? error.message : error);
    return letterContent;
  }
}