/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AgencyDataSource = "admin_manual" | "ai_verified" | "ontario_open_data";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AuditActionType = "BUG_FIX" | "CHALLENGE_INITIATED" | "CHALLENGE_UPDATED" | "CONFIG_UPDATE" | "CREATE" | "DATA_EXPORT" | "DELETE" | "DOWNLOAD" | "ESCALATION_TRIGGERED" | "EXHAUSTION_REACHED" | "FEATURE_ADDED" | "FEATURE_REMOVED" | "LOGIN" | "LOGIN_FAILED" | "LOGOUT" | "PACKET_GENERATED" | "READ" | "RESPONSE_RECORDED" | "SCHEMA_CHANGE" | "SETTINGS_CHANGED" | "SYSTEM_CHANGE" | "UPDATE" | "UPLOAD";

export type AuditEntityType = "BUREAU" | "ENFORCEMENT_MECHANISM" | "EVIDENCE_EVENT" | "FURNISHER" | "FURNISHER_OBLIGATION" | "FURNISHER_VALIDATION" | "METRO2_VALIDATION_LOG" | "OBLIGATION" | "OBLIGATION_INSTANCE" | "PACKET" | "REGULATORY_UPDATE" | "REPORT_ARTIFACT" | "STATUTE" | "SYSTEM" | "TRADELINE" | "USER_ACCOUNT";

export type AuditStatus = "FAILURE" | "SUCCESS";

export type BankruptcyStatus = "ACTIVE" | "COMPLETED" | "DISCHARGED" | "PENDING_REMOVAL" | "REMOVED";

export type BankruptcyType = "BANKRUPTCY_DISCHARGED" | "BANKRUPTCY_NOT_DISCHARGED" | "CONSUMER_PROPOSAL" | "DIVISION_I_PROPOSAL" | "PERSONAL_BANKRUPTCY";

export type BetaIssueCategory = "BUG" | "COMPLIANCE" | "DATA_ISSUE" | "FEATURE_GAP" | "OTHER" | "PERFORMANCE" | "UI_ISSUE";

export type BetaIssueSeverity = "CRITICAL" | "HIGH" | "LOW" | "MEDIUM";

export type BetaIssueStatus = "ANALYZED" | "ANALYZING" | "DISMISSED" | "OPEN" | "RESOLVED";

export type CanadianProvince = "AB" | "BC" | "MB" | "NB" | "NL" | "NS" | "NT" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT";

export type ConsumerStatementType = "active_duty_alert" | "dispute" | "fraud_alert" | "general_statement" | "identity_theft" | "security_freeze";

export type CraObligationType = "ACCURACY_INTEGRITY" | "CORRECTION_DUTY" | "DATA_VALIDATION" | "DISPUTE_INVESTIGATION" | "DOFD_REPORTING" | "MONTHLY_REPORTING";

export type DisclosureCategory = "CONTENT" | "IDENTITY" | "RIGHTS" | "SOURCES";

export type DiscriminationGround = "AGE" | "COLOUR" | "CONVICTION_PARDONED" | "DISABILITY" | "FAMILY_STATUS" | "GENDER_IDENTITY_EXPRESSION" | "GENETIC_CHARACTERISTICS" | "MARITAL_STATUS" | "NATIONAL_ETHNIC_ORIGIN" | "OTHER" | "RACE" | "RELIGION" | "SEX" | "SEXUAL_ORIENTATION";

export type DynamicRuleStatus = "ACTIVE" | "ARCHIVED" | "PROPOSED" | "REJECTED";

export type EcoaCode = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "P" | "S" | "T" | "U" | "W" | "X" | "Z";

export type EnforcementMechanismType = "COMPLAINT_PROCEDURE" | "ENFORCING_BODY" | "PENALTY";

export type ExtractionPassStatus = "completed" | "failed" | "pending";

export type ExtractionPassType = "A" | "A_FULL" | "B";

export type FeatureFlagScope = "admin" | "global" | "user";

export type FreezeStatus = "active" | "cancelled" | "expired" | "requested" | "thawed";

export type FreezeType = "extended_fraud_alert" | "fraud_alert" | "security_freeze";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type InquiryType = "account_review" | "hard" | "promotional" | "soft" | "unknown";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KnownEntityType = "account_type" | "creditor_name" | "province" | "remark_code" | "status_code";

export type LetterTemplateCategory = "bureau" | "provincial" | "violation_narrative";

export type LicenseStatus = "active" | "expired" | "revoked" | "suspended";

export type MigrationStatus = "applied" | "pending" | "rolled_back";

export type Numeric = ColumnType<string, number | string, number | string>;

export type ObligationSection = "BILL_COLLECTOR" | "CREDIT_BUREAU" | "CREDITOR";

export type ObligationState = "ADDRESSED_VIA_LINKED_DISPUTE" | "CHALLENGED" | "INSUFFICIENT_RESPONSE" | "NO_RESPONSE" | "OBLIGATION_PENDING" | "PROCEDURALLY_EXHAUSTED";

export type PacketProcessingStatus = "completed" | "failed" | "generating" | "pending" | "uploading";

export type PostalTransactionStatus = "completed" | "failed" | "pending" | "refunded";

export type PublicRecordType = "bankruptcy" | "civil_judgment" | "foreclosure" | "judgment" | "other" | "tax_lien" | "wage_garnishment";

export type RegulatoryChangeType = "CASE_LAW" | "ENFORCEMENT_CHANGE" | "NEW_REGULATION" | "NEW_STATUTE" | "PROCEDURAL_CHANGE" | "REGULATION_AMENDMENT" | "STATUTE_AMENDMENT" | "STATUTE_REPEAL";

export type RegulatoryUpdateSource = "AUTOMATED_SCAN" | "COURT_DECISION" | "GOVERNMENT_NOTICE" | "INDUSTRY_BULLETIN" | "LEGAL_NEWSLETTER" | "MANUAL_ENTRY";

export type RegulatoryUpdateStatus = "APPLIED" | "ARCHIVED" | "DETECTED" | "DISMISSED" | "UNDER_REVIEW" | "VERIFIED";

export type ResponsibilityCode = "authorized_user" | "cosigner" | "individual" | "joint" | "on_behalf_of" | "terminated" | "unknown";

export type SignatureType = "document_signing" | "freeze_authorization" | "identity_verification" | "thaw_authorization";

export type SubscriptionPlan = "annual" | "beta" | "monthly";

export type SubscriptionStatus = "active" | "cancelled" | "expired" | "past_due" | "trialing";

export type SupportTicketCategory = "ACCOUNT" | "BILLING" | "DISPUTE_HELP" | "OTHER" | "TECHNICAL";

export type SupportTicketPriority = "HIGH" | "LOW" | "MEDIUM" | "URGENT";

export type SupportTicketStatus = "CLOSED" | "IN_PROGRESS" | "OPEN" | "RESOLVED" | "WAITING_ON_USER";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "support" | "user";

export type ValidationSeverity = "ERROR" | "INFO" | "WARNING";

export type VersionStatus = "archived" | "draft" | "released" | "staged";

export type ViolationCategory = "ACCOUNT_STATUS_INCONSISTENCY" | "BALANCE_CALCULATION_VIOLATION" | "BANKRUPTCY_DISCHARGE_VIOLATION" | "BUREAU_ACCESS_VIOLATION" | "BUREAU_DISPUTE_MARKING_FAILURE" | "BUREAU_INVESTIGATION_FAILURE" | "BUREAU_NOTIFICATION_FAILURE" | "BUREAU_REINSERTION_VIOLATION" | "CLOSED_ACCOUNT_BALANCE_INFLATION" | "COLLECTION_LIMITATION_EXCEEDED" | "COLLECTOR_DUPLICATE_REPORTING" | "COLLECTOR_LICENSE_FAILURE" | "COLLECTOR_PAYMENT_ACKNOWLEDGMENT_VIOLATION" | "COLLECTOR_STATUTE_REVIVAL_ATTEMPT" | "COLLECTOR_UNAUTHORIZED_FEES" | "CONSENT_WITHDRAWAL_NOT_HONORED" | "CONSUMER_STATEMENT_SUPPRESSION" | "CREDIT_LIMIT_MANIPULATION" | "CREDITOR_RESPONSE_QUALITY" | "CROSS_BUREAU_INCONSISTENCY" | "CROSS_ENTITY_DISCREPANCY" | "DATE_LOGIC_IMPOSSIBLE" | "DISCLOSURE_DEFICIENCY" | "DOCUMENTATION_CHAIN_FAILURE" | "FREEZE_PERIOD_VIOLATION" | "FURNISHER_AUTHORIZED_USER_MISREPRESENTATION" | "FURNISHER_JOINT_ACCOUNT_VIOLATION" | "FURNISHER_POST_DISPUTE_RETALIATION" | "FURNISHER_REAGING_VIOLATION" | "FURNISHER_RESPONSE_QUALITY" | "FURNISHER_STATUS_CODE_MISMATCH" | "IDENTITY_THEFT_VIOLATION" | "INVESTIGATION_RUBBER_STAMP" | "LAST_ACTIVITY_DATE_MANIPULATION" | "MIXED_FILE_PERSONAL_INFO_MISMATCH" | "MULTIPLE_COLLECTOR_VIOLATION" | "PAYMENT_HISTORY_MANIPULATION" | "PHANTOM_DEBT_UNVERIFIABLE" | "PROCEDURAL_TIMING_VIOLATION" | "RESPONSE_ADDRESS_MISMATCH" | "RESPONSE_INCOMPLETE" | "RESPONSE_MOV_MISSING" | "RESPONSE_NO_DOCUMENTATION" | "RESPONSE_UNAUTHORIZED" | "RETROACTIVE_HISTORY_MANIPULATION" | "STALE_REPORTING_FAILURE" | "STATUTE_APPROACHING" | "STATUTE_OF_LIMITATIONS" | "TEMPORAL_MANIPULATION" | "ZOMBIE_DEBT_RESURRECTION";

export type ViolationUserStatus = "active" | "dismissed" | "verified";

export interface AuditLog {
  actionType: AuditActionType;
  details: Json | null;
  entityId: number | null;
  entityType: AuditEntityType;
  errorMessage: string | null;
  id: Generated<number>;
  ipAddress: string | null;
  region: Generated<string>;
  status: Generated<AuditStatus>;
  timestamp: Generated<Timestamp>;
  userAgent: string | null;
  userId: number | null;
}

export interface BankruptcyRecord {
  actualRemovalDate: Timestamp | null;
  bankruptcyType: BankruptcyType;
  caseNumber: string | null;
  completionDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  dischargeDate: Timestamp | null;
  equifaxReporting: Generated<boolean | null>;
  expectedRemovalDate: Timestamp;
  filingCourt: string | null;
  filingDate: Timestamp;
  id: Generated<number>;
  notes: string | null;
  organizationId: number | null;
  province: CanadianProvince;
  region: Generated<string>;
  retentionMonths: Generated<number>;
  retentionRuleDescription: string | null;
  retentionYears: number;
  status: Generated<BankruptcyStatus>;
  tradelineId: number | null;
  transunionReporting: Generated<boolean | null>;
  updatedAt: Generated<Timestamp | null>;
  userId: number | null;
}

export interface BetaIssueReport {
  actualBehavior: string | null;
  adminNotes: string | null;
  aiAffectedComponents: Generated<Json | null>;
  aiAnalysis: string | null;
  aiSuggestedFix: string | null;
  analyzedAt: Timestamp | null;
  browserInfo: string | null;
  category: Generated<BetaIssueCategory>;
  createdAt: Generated<Timestamp>;
  description: string;
  expectedBehavior: string | null;
  id: Generated<number>;
  pageUrl: string | null;
  resolvedAt: Timestamp | null;
  severity: Generated<BetaIssueSeverity>;
  status: Generated<BetaIssueStatus>;
  stepsToReproduce: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Bureau {
  address: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  postalCode: string | null;
  province: string | null;
  region: Generated<string>;
}

export interface ComplianceConfig {
  confidenceThreshold: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  enabled: Generated<boolean | null>;
  id: Generated<number>;
  recommendedActionTemplate: string | null;
  updatedAt: Generated<Timestamp | null>;
  updatedByUserId: number | null;
  userExplanationTemplate: string | null;
  violationCategory: ViolationCategory;
}

export interface ConsumerSignature {
  associatedFreezeId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isVerified: Generated<boolean>;
  metadata: Generated<Json | null>;
  signatureData: string;
  signatureType: SignatureType;
  userId: number;
  verifiedAt: Timestamp | null;
  verifiedBy: number | null;
}

export interface ConsumerIdentificationDocument {
  fileName: string;
  fileSizeBytes: number;
  fileType: string;
  id: Generated<number>;
  region: Generated<string>;
  sha256: string;
  storageUrl: string;
  updatedAt: Generated<Timestamp>;
  uploadedAt: Generated<Timestamp>;
  userId: number;
}

export interface Creditor {
  address: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
}

export interface CreditorObligationTest {
  autoGenerated: Generated<boolean | null>;
  confidenceScore: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  creditorId: number | null;
  detectedAt: Generated<Timestamp | null>;
  disputeVector: string | null;
  escalationPath: string | null;
  id: Generated<number>;
  lastChallengeDate: Timestamp | null;
  lastTestDate: Timestamp | null;
  metro2Version: string | null;
  notes: string | null;
  obligationSequence: Generated<number | null>;
  obligationState: Generated<ObligationState | null>;
  obligationType: CraObligationType;
  omissions: string | null;
  recommendedAction: string | null;
  responseDeadline: Timestamp | null;
  responsesReceived: Generated<number | null>;
  severity: Generated<string | null>;
  statutoryBasis: string | null;
  technicalDetails: Json | null;
  tradelineId: number | null;
  updatedAt: Generated<Timestamp | null>;
  userExplanation: string | null;
  userStatus: Generated<ViolationUserStatus>;
  userStatusReason: string | null;
  userStatusUpdatedAt: Timestamp | null;
  validationStatus: string | null;
  violationCategory: ViolationCategory | null;
}

export interface ViolationCorrection {
  adminNotes: string | null;
  correctedConfidence: number | null;
  correctedExplanation: string | null;
  correctedSeverity: string | null;
  correctedSummary: string | null;
  correctedViolationType: string | null;
  correctionAction: string;
  correctionReason: string | null;
  createdAt: Generated<Timestamp>;
  createdByAdminId: number;
  extractionRunId: number;
  finalReviewedAt: Timestamp | null;
  finalizedByAdminId: number | null;
  id: Generated<number>;
  originalViolationId: number | null;
  status: Generated<string>;
  tradelineId: number;
  trainingLabel: string | null;
  trainingNoteOnly: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  useForTraining: Generated<boolean>;
}

export interface ViolationCorrectionEvidence {
  adminSelected: Generated<boolean>;
  correctionId: number;
  createdAt: Generated<Timestamp>;
  evidenceReason: string;
  extractionRunId: number;
  fieldName: string | null;
  id: Generated<number>;
  normalizedValue: string | null;
  pageNumber: number;
  sourceDocumentId: number;
  textExcerpt: string;
  tradelineId: number;
}

export interface ViolationRegulationReference {
  adminNotes: string | null;
  adminVerifiedCitation: Generated<boolean>;
  citationConfidence: Generated<number>;
  citationSource: string;
  citationUrl: string | null;
  correctionId: number | null;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  extractionRunId: number;
  id: Generated<number>;
  jurisdiction: string;
  mappingStatus: Generated<string>;
  provinceOrTerritory: string | null;
  regulationName: string;
  regulationTextExcerpt: string;
  regulatorOrStandardBody: string;
  sectionNumber: string;
  statuteOrRuleName: string;
  subsectionNumber: string | null;
  tradelineId: number | null;
  updatedAt: Generated<Timestamp>;
  violationId: number | null;
}

export interface ViolationTrainingExample {
  correctionId: number;
  createdAt: Generated<Timestamp>;
  expectedOutputJson: Json;
  id: Generated<number>;
  inputContextJson: Json;
  label: string;
  regulationMappingJson: Generated<Json>;
  updatedAt: Generated<Timestamp>;
  useForTraining: Generated<boolean>;
}

export interface CreditorValidationRequirement {
  createdAt: Generated<Timestamp>;
  creditorId: number | null;
  description: string;
  id: Generated<number>;
  lastValidationDate: Timestamp | null;
  notes: string | null;
  obligationType: CraObligationType;
  region: Generated<string>;
  statutoryReference: string | null;
  timeframeDays: number | null;
  validationStatus: string | null;
}

export interface DeadlineEvent {
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  deadline: Timestamp;
  description: string | null;
  eventType: string;
  id: Generated<number>;
  isCompleted: Generated<boolean | null>;
  obligationInstanceId: number | null;
  organizationId: number | null;
  packetId: number | null;
  region: Generated<string>;
  title: string;
}

export interface DisclosureRequirement {
  category: DisclosureCategory;
  createdAt: Generated<Timestamp>;
  description: string;
  fieldPath: string | null;
  id: Generated<number>;
  metadata: Generated<Json | null>;
  requirementCode: string;
  sectionReference: string | null;
  severity: Generated<string>;
  statuteVersionId: number;
}

export interface DiscriminationClaim {
  allegedDiscriminationDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  evidenceSummary: string | null;
  grounds: ArrayType<DiscriminationGround>;
  id: Generated<number>;
  obligationInstanceId: number | null;
  packetId: number | null;
  region: Generated<string | null>;
  reportedDate: Generated<Timestamp | null>;
  resolution: string | null;
  resolvedDate: Timestamp | null;
  status: Generated<string | null>;
  tradelineId: number;
}

export interface DynamicScanningRule {
  approvedAt: Timestamp | null;
  approvedBy: number | null;
  confidenceScore: Generated<Numeric>;
  createdAt: Generated<Timestamp | null>;
  description: string;
  id: Generated<number>;
  recommendedActionTemplate: string;
  regulatoryUpdateId: number | null;
  ruleDefinition: Json;
  severity: Generated<string>;
  status: Generated<DynamicRuleStatus>;
  statutoryBasis: string | null;
  title: string;
  updatedAt: Generated<Timestamp | null>;
  userExplanationTemplate: string;
  violationCategory: string;
}

export interface EmailVerificationTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  token: string;
  userId: number;
  verified: Generated<boolean>;
}

export interface EnforcementMechanism {
  contactInfo: string | null;
  createdAt: Generated<Timestamp | null>;
  description: string;
  filingDeadlineDays: number | null;
  id: Generated<number>;
  jurisdiction: string;
  mechanismType: EnforcementMechanismType;
  name: string;
  notes: string | null;
  penaltyAmount: string | null;
  region: Generated<string>;
  statutoryReference: string | null;
  websiteUrl: string | null;
}

export interface EvidenceAttachment {
  description: string | null;
  fileName: string;
  fileSizeBytes: number;
  fileType: string;
  id: Generated<number>;
  obligationInstanceId: number | null;
  packetId: number | null;
  region: Generated<string>;
  storageUrl: string;
  uploadedAt: Generated<Timestamp>;
  uploadedBy: number | null;
}

export interface EvidenceEvent {
  at: Generated<Timestamp | null>;
  currentHash: string | null;
  description: string | null;
  eventType: string;
  id: Generated<number>;
  organizationId: number | null;
  packetId: number | null;
  previousHash: string | null;
  region: Generated<string>;
  statuteVersionId: number | null;
}

export interface FeatureFlag {
  createdAt: Generated<Timestamp>;
  description: string | null;
  enabled: Generated<boolean>;
  id: Generated<number>;
  key: string;
  label: string;
  maxVersion: string | null;
  minVersion: string | null;
  scope: Generated<FeatureFlagScope>;
  updatedAt: Generated<Timestamp>;
}

export interface FederalGuidance {
  createdAt: Generated<Timestamp>;
  description: string | null;
  effectiveDate: Timestamp;
  guidanceCode: string;
  id: Generated<number>;
  metadata: Json | null;
  region: Generated<string>;
  sectionReference: string | null;
  sourceUrl: string;
  supersededDate: Timestamp | null;
  title: string;
  version: Generated<number>;
}

export interface IdentityTheftFreeze {
  bureauId: number | null;
  createdAt: Generated<Timestamp>;
  effectiveDate: Timestamp | null;
  expirationDate: Timestamp | null;
  freezeType: FreezeType;
  id: Generated<number>;
  notes: string | null;
  region: Generated<string>;
  requestDate: Generated<Timestamp>;
  status: Generated<FreezeStatus>;
  thawDate: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
  verificationDocuments: Generated<Json | null>;
}

export interface IndustryStandard {
  createdAt: Generated<Timestamp>;
  description: string | null;
  documentationUrl: string | null;
  effectiveDate: Timestamp;
  fieldMappings: Json | null;
  id: Generated<number>;
  metadata: Json | null;
  region: Generated<string>;
  segmentDefinitions: Json | null;
  sourceUrl: string;
  standardCode: string;
  standardName: string;
  supersededDate: Timestamp | null;
  validationRules: Json | null;
  version: string;
}

export interface LeadReminder {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  remindedAt: Timestamp | null;
  source: Generated<string>;
}

export interface LetterTemplate {
  category: LetterTemplateCategory;
  certification: string | null;
  closing: string | null;
  consumerStatementRight: string | null;
  fullBodyOverride: string | null;
  id: Generated<number>;
  introduction: string | null;
  isActive: Generated<boolean>;
  label: string;
  requestedAction: string | null;
  sourceUrl: string | null;
  statutoryGrounds: string | null;
  statutoryReference: string | null;
  statutoryTimeframe: string | null;
  subject: string | null;
  templateKey: string;
  updatedAt: Generated<Timestamp>;
  updatedBy: number | null;
}

export interface LicensedCollectionAgency {
  agencyName: string;
  agencyNameNormalized: string;
  createdAt: Generated<Timestamp>;
  dataSource: AgencyDataSource;
  id: Generated<number>;
  licenseExpiryDate: Timestamp | null;
  licenseNumber: string | null;
  licenseStatus: Generated<LicenseStatus>;
  province: string;
  updatedAt: Generated<Timestamp>;
  verifiedAt: Timestamp | null;
}

export interface LoginAttempts {
  attemptedAt: Timestamp;
  email: string;
  id: Generated<number>;
  success: boolean;
}

export interface Metro2ValidationLog {
  actualValue: string | null;
  expectedValue: string | null;
  id: Generated<number>;
  message: string;
  metro2Version: string | null;
  region: Generated<string>;
  ruleCategory: string;
  ruleName: string;
  severity: ValidationSeverity;
  tradelineId: number | null;
  validatedAt: Generated<Timestamp>;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: Generated<string>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
}

export interface Obligation {
  createdAt: Generated<Timestamp | null>;
  description: string;
  dutyType: string | null;
  id: Generated<number>;
  isStatutory: Generated<boolean>;
  jurisdiction: string | null;
  notes: string | null;
  obligationType: string | null;
  region: string | null;
  section: Generated<ObligationSection>;
  statutoryReference: string | null;
  timeframeDays: number | null;
}

export interface ObligationChallengeLog {
  actualValue: string | null;
  challengeBasis: string;
  challengeVector: string | null;
  comparisonSnapshotId: number | null;
  deficiencies: string | null;
  detectedAt: Generated<Timestamp | null>;
  expectedValue: string | null;
  fieldName: string | null;
  id: Generated<number>;
  message: string;
  packetId: number | null;
  region: Generated<string | null>;
  reportArtifactId: number | null;
  responseDate: Timestamp | null;
  responseReceived: Generated<boolean | null>;
  ruleCategory: string | null;
  severity: ValidationSeverity;
  sourceSnapshotId: number | null;
  timingDriftDays: number | null;
  tradelineId: number | null;
}

export interface ObligationInstance {
  challengeSentDate: Timestamp | null;
  createdAt: Generated<Timestamp | null>;
  disputeVector: string | null;
  escalationDate: Timestamp | null;
  escalationTriggered: Generated<boolean | null>;
  id: Generated<number>;
  notes: string | null;
  obligationId: number | null;
  organizationId: number | null;
  pressureScore: Numeric | null;
  responseAuditCompletedAt: Timestamp | null;
  responseAuditFindings: Generated<Json | null>;
  responseAuthorizedSignature: boolean | null;
  responseDeadline: Timestamp | null;
  responseDocumentationProvided: boolean | null;
  responseDocumentationTypes: Generated<Json | null>;
  responseExpectedAddress: string | null;
  responseItemsAddressed: Generated<Json | null>;
  responseItemsDisputed: Generated<Json | null>;
  responseLetterContent: string | null;
  responseMovDescription: string | null;
  responseMovDisclosed: boolean | null;
  responseReceivedDate: Timestamp | null;
  responseSenderAddress: string | null;
  responseSignatoryName: string | null;
  responseSignatoryTitle: string | null;
  responseStatus: string | null;
  state: ObligationState | null;
  successOutcome: string | null;
  tradelineId: number | null;
  userId: number | null;
}

export interface Organizations {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
  region: Generated<string>;
}

export interface Packet {
  baselineSnapshotId: number | null;
  bureauId: number | null;
  bureauResponseDate: Timestamp | null;
  consumerCertification: Generated<boolean | null>;
  content: string | null;
  createdAt: Generated<Timestamp | null>;
  creditorObligationTestId: number | null;
  deliveryMethod: string | null;
  id: Generated<number>;
  letterDate: Timestamp | null;
  organizationId: number | null;
  pdfStorageUrl: string | null;
  postgridLetterId: Generated<string | null>;
  processingStatus: Generated<PacketProcessingStatus>;
  recipientAddressLine1: string | null;
  recipientAddressLine2: string | null;
  recipientCity: string | null;
  recipientName: string | null;
  recipientPostalCode: string | null;
  recipientProvince: string | null;
  region: Generated<string | null>;
  responseType: string | null;
  sentDate: Timestamp | null;
  signatureMode: string | null;
  status: string | null;
  statuteVersionId: number | null;
  successOutcome: string | null;
  terminalLabel: string | null;
  trackingNumber: string | null;
  tradelineId: number | null;
  type: string | null;
  userId: number | null;
}

export interface PacketComplianceAudit {
  appliedAt: Generated<Timestamp | null>;
  complianceStatus: Generated<string>;
  createdAt: Generated<Timestamp | null>;
  evidenceEventId: number | null;
  id: Generated<number>;
  obligationId: number | null;
  packetId: number;
  region: Generated<string | null>;
  regulationType: string | null;
  selectionReason: string | null;
  statuteVersionId: number | null;
}

export interface PacketImpactAssessment {
  assessedAt: Generated<Timestamp>;
  assessmentType: string;
  baselineSnapshotId: number;
  favorableChanges: Generated<number>;
  fieldDiffs: Generated<Json>;
  followupSnapshotId: number;
  id: Generated<number>;
  impactScore: Numeric | null;
  neutralChanges: Generated<number>;
  notes: string | null;
  packetId: number;
  totalFieldsChanged: Generated<number>;
  tradelineId: number;
  unfavorableChanges: Generated<number>;
}

export interface ParserBureauDetectionConfig {
  bureau: string;
  createdBy: number | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  marker: string;
  updatedAt: Generated<Timestamp>;
  weight: Generated<number>;
}

export interface ParserFieldMapping {
  bureau: string;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  priority: Generated<number>;
  section: string;
  sourcePath: string;
  targetField: string;
  transformConfig: Json | null;
  transformType: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ParserKnownEntity {
  createdAt: Generated<Timestamp | null>;
  createdBy: number | null;
  description: string | null;
  entityType: KnownEntityType;
  id: Generated<number>;
  value: string;
}

export interface ParserMappingVersion {
  changedAt: Generated<Timestamp>;
  changedBy: number | null;
  changeType: string;
  id: Generated<number>;
  mappingId: number | null;
  newState: Json | null;
  notes: string | null;
  previousState: Json | null;
  versionNumber: number;
}

export interface ParserRuleCandidate {
  activatedRuleId: number | null;
  approvedValue: Json | null;
  bureau: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  decisionId: string;
  entityKey: string | null;
  entityType: string;
  fieldPath: string;
  id: Generated<number>;
  parsedValue: Json | null;
  parserInstruction: string | null;
  parserMode: string | null;
  ruleConfig: Generated<Json>;
  ruleType: string;
  sourceEvidence: string | null;
  stageVersion: string | null;
  status: Generated<string>;
  testCaseId: number;
  updatedAt: Generated<Timestamp>;
  validationSummary: Json | null;
}

export interface ParserExtractionRule {
  bureau: string;
  config: Generated<Json>;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  createdFromCandidateId: number | null;
  description: string | null;
  fieldPath: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  priority: Generated<number>;
  ruleType: string;
  targetField: string;
  updatedAt: Generated<Timestamp>;
}

export interface ParserTestCase {
  adjudicationDecisions: Generated<Json | null>;
  adminReviewStatus: Generated<string>;
  allowAiFallback: boolean | null;
  approvedConsumerInfo: Json | null;
  approvedTradelines: Generated<Json | null>;
  bureau: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: number;
  description: string | null;
  expectedConsumerInfo: Json | null;
  expectedTradelines: Generated<Json | null>;
  extractionSource: string | null;
  id: Generated<number>;
  lastRunAt: Timestamp | null;
  lastRunPassed: boolean | null;
  name: string;
  parserContext: Generated<Json | null>;
  parserMode: string | null;
  pdfBase64: string;
  rawExtractedText: string | null;
  stageVersion: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ParserTestRun {
  actualConsumerInfo: Json | null;
  actualTradelines: Generated<Json | null>;
  fieldResults: Generated<Json | null>;
  id: Generated<number>;
  passed: Generated<boolean>;
  patternSuggestions: Generated<Json | null>;
  runAt: Generated<Timestamp>;
  testCaseId: number;
}

export interface PassAEditLog {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  op: string;
  path: string;
  reason: string | null;
  reportArtifactId: number;
  sourceTimestamp: Generated<Timestamp>;
  sourceType: Generated<string>;
  value: Json | null;
}

export interface PassExtraction {
  accounts: Json | null;
  bureauContext: Json | null;
  channelConfidence: number | null;
  channelGuess: string | null;
  completedAt: Timestamp | null;
  conflicts: Generated<Json | null>;
  consumerProfile: Json | null;
  createdAt: Generated<Timestamp | null>;
  errorDetails: Json | null;
  errorMessage: string | null;
  id: Generated<number>;
  inquiriesCreditRelated: Json | null;
  inquiriesOther: Json | null;
  insolvencyPublicRecords: Json | null;
  missingRequiredFields: Generated<Json | null>;
  pass: Generated<ExtractionPassType>;
  portalSummary: Json | null;
  qualityNotes: Generated<Json | null>;
  rawEvidence: Generated<Json | null>;
  reportArtifactId: number;
  startedAt: Timestamp | null;
  status: Generated<ExtractionPassStatus>;
}

export interface PasswordResetTokens {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<number>;
  token: string;
  used: Generated<boolean>;
  userId: number;
}

export interface PostalTransaction {
  amountCad: Numeric;
  baseCostCad: Numeric | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  markupCad: Generated<Numeric | null>;
  packetId: number | null;
  postgridLetterId: string | null;
  status: Generated<PostalTransactionStatus>;
  stripePaymentIntentId: string | null;
  surchargeCad: Numeric | null;
  userId: number;
}

export interface RateLimitEntry {
  action: string;
  count: Generated<number>;
  identifier: string;
  resetAt: Timestamp;
}

export interface RegulatoryNotification {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isRead: Generated<boolean>;
  message: string;
  notificationType: string;
  readAt: Timestamp | null;
  region: Generated<string>;
  regulatoryUpdateId: number | null;
  severity: Generated<string>;
  title: string;
  userId: number | null;
}

export interface RegulatoryUpdateLog {
  actionRequired: string | null;
  appliedAt: Timestamp | null;
  changeType: RegulatoryChangeType;
  createdAt: Generated<Timestamp | null>;
  description: string;
  detectedAt: Generated<Timestamp | null>;
  effectiveDate: Timestamp | null;
  id: Generated<number>;
  impactAssessment: string | null;
  jurisdiction: string;
  notes: string | null;
  region: Generated<string>;
  reviewedAt: Timestamp | null;
  reviewedBy: string | null;
  source: RegulatoryUpdateSource;
  sourceUrl: string | null;
  status: Generated<RegulatoryUpdateStatus>;
  statutoryReference: string | null;
  title: string;
}

export interface ReportArtifact {
  artifactType: string | null;
  createdAt: Generated<Timestamp | null>;
  crrgYear: number | null;
  data: Json | null;
  expiresAt: Timestamp | null;
  id: Generated<number>;
  metro2Version: string | null;
  organizationId: number | null;
  processingStatus: Generated<string>;
  region: Generated<string | null>;
  reportDate: Timestamp | null;
  sha256: string | null;
  storageUrl: string | null;
  tradelineId: number | null;
  userId: number | null;
  validationRulesApplied: Generated<Json | null>;
}

export interface ReportConsumerInfo {
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  confidenceScore: Generated<number | null>;
  createdAt: Generated<Timestamp | null>;
  dateOfBirth: Timestamp | null;
  dateOfBirthRaw: string | null;
  dependentsCount: number | null;
  fileNumber: string | null;
  firstName: string | null;
  fullName: string | null;
  id: Generated<number>;
  lastName: string | null;
  middleName: string | null;
  phone: string | null;
  phoneSecondary: string | null;
  postalCode: string | null;
  previousAddresses: Generated<Json | null>;
  previousNames: Generated<Json | null>;
  province: string | null;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  reportDate: Timestamp | null;
  sinLastDigits: string | null;
  spouseName: string | null;
  suffix: string | null;
}

export interface ReportConsumerStatement {
  addedDate: Timestamp | null;
  associatedInquiryId: number | null;
  associatedTradelineId: number | null;
  createdAt: Generated<Timestamp | null>;
  effectiveDate: Timestamp | null;
  expirationDate: Timestamp | null;
  id: Generated<number>;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  statementText: string | null;
  statementType: ConsumerStatementType;
}

export interface ReportCreditScore {
  bureauName: string | null;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  scoreDate: Timestamp | null;
  scoreFactors: Generated<Json | null>;
  scoreRangeMax: number | null;
  scoreRangeMin: number | null;
  scoreType: string;
  scoreValue: number | null;
}

export interface ReportEmploymentInfo {
  createdAt: Generated<Timestamp | null>;
  employerAddress: string | null;
  employerCity: string | null;
  employerName: string | null;
  employerPhone: string | null;
  employerPostalCode: string | null;
  employerProvince: string | null;
  employmentStatus: string | null;
  hireDate: Timestamp | null;
  id: Generated<number>;
  isCurrent: Generated<boolean | null>;
  occupation: string | null;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  salary: Numeric | null;
  salaryFrequency: string | null;
  terminationDate: Timestamp | null;
  verifiedDate: Timestamp | null;
}

export interface ReportInquiry {
  createdAt: Generated<Timestamp | null>;
  creditorName: string | null;
  id: Generated<number>;
  industryCode: string | null;
  inquiryDate: Timestamp | null;
  inquiryPurpose: string | null;
  inquiryType: Generated<InquiryType>;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  subscriberCode: string | null;
}

export interface ReportPublicRecord {
  amount: Numeric | null;
  assetAmount: Numeric | null;
  attorney: string | null;
  bankruptcyType: string | null;
  caseNumber: string | null;
  courtLocation: string | null;
  courtName: string | null;
  createdAt: Generated<Timestamp | null>;
  dischargeDate: Timestamp | null;
  exemptAmount: Numeric | null;
  filingDate: Timestamp | null;
  id: Generated<number>;
  liabilityAmount: Numeric | null;
  plaintiff: string | null;
  rawSectionText: string | null;
  recordType: PublicRecordType;
  region: Generated<string>;
  releaseDate: Timestamp | null;
  reportArtifactId: number;
  satisfiedDate: Timestamp | null;
  status: string | null;
  trustee: string | null;
  verifiedDate: Timestamp | null;
}

export interface Sessions {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Timestamp;
  userId: number;
}

export interface SoftwareVersion {
  codeLineCount: number | null;
  codename: string | null;
  createdAt: Generated<Timestamp>;
  createdBy: number | null;
  id: Generated<number>;
  locked: Generated<boolean>;
  releasedAt: Timestamp | null;
  releaseNotes: Generated<Json | null>;
  status: Generated<VersionStatus>;
  systemSnapshot: Json | null;
  updatedAt: Generated<Timestamp>;
  version: string;
}

export interface Statute {
  code: string;
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  jurisdiction: string;
  region: Generated<string>;
}

export interface StatuteVersion {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  effectiveDate: Timestamp;
  id: Generated<number>;
  region: Generated<string>;
  responseClockDays: number | null;
  sectionReference: string | null;
  sourceUrl: string | null;
  statuteId: number;
  supersededDate: Timestamp | null;
  version: Generated<number>;
}

export interface Subscriptions {
  cancelledAt: Timestamp | null;
  cancelReason: string | null;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp | null;
  currentPeriodStart: Timestamp | null;
  id: Generated<number>;
  plan: Generated<SubscriptionPlan>;
  priceCad: Numeric | null;
  renewalReminderSentAt: Timestamp | null;
  status: Generated<SubscriptionStatus>;
  stripeCustomerId: string | null;
  stripeSubscriptionId: string | null;
  trialEnd: Generated<Timestamp>;
  trialStart: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface SuccessMetric {
  bureauId: number | null;
  creditorId: number | null;
  disputeVector: string | null;
  escalationCount: Generated<number | null>;
  finalState: string | null;
  id: Generated<number>;
  obligationInstanceId: number | null;
  outcome: string;
  recordedAt: Generated<Timestamp>;
  region: Generated<string>;
  responseTimeDays: number | null;
  violationCategory: string | null;
}

export interface SupportTicket {
  assignedAgentId: number | null;
  category: Generated<SupportTicketCategory>;
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<number>;
  priority: Generated<SupportTicketPriority>;
  region: Generated<string>;
  resolvedAt: Timestamp | null;
  status: Generated<SupportTicketStatus>;
  subject: string;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface SupportTicketMessage {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  isInternalNote: Generated<boolean>;
  message: string;
  senderId: number;
  senderRole: UserRole;
  ticketId: number;
}

export interface SuspiciousActivityLog {
  blocked: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  fingerprintHash: string;
  id: Generated<number>;
  ipAddress: string | null;
  reason: string;
  userAgent: string | null;
}

export interface SystemSettings {
  description: string | null;
  key: string;
  updatedAt: Generated<Timestamp>;
  updatedByUserId: number | null;
  value: string;
}

export interface Tradeline {
  accountDesignation: string | null;
  accountNumber: string;
  accountType: string | null;
  actualPaymentAmount: Numeric | null;
  amountPastDue: Numeric | null;
  amountWrittenOff: Numeric | null;
  balance: Numeric | null;
  balloonPaymentDate: Timestamp | null;
  bureauId: number | null;
  chargeOffDate: Timestamp | null;
  collectionAgencyName: string | null;
  createdAt: Generated<Timestamp | null>;
  creditLimit: Numeric | null;
  creditorId: number | null;
  creditorPhone: string | null;
  currentBalance: Numeric | null;
  dateAssignedToCollection: Timestamp | null;
  dateClosed: Timestamp | null;
  dateOfFirstDelinquency: Timestamp | null;
  dateOfLastPayment: Timestamp | null;
  datePaidSettled: Timestamp | null;
  dateVerified: Timestamp | null;
  ecoaCode: string | null;
  hasJ1Segment: Generated<boolean | null>;
  hasJ2Segment: Generated<boolean | null>;
  highCredit: Numeric | null;
  id: Generated<number>;
  interestRate: Numeric | null;
  isCollectionAccount: Generated<boolean | null>;
  j1ConsumerName: string | null;
  j2ConsumerName: string | null;
  lastActivityDate: Timestamp | null;
  lastDisputeVectors: Generated<Json | null>;
  lastPaymentAmount: Numeric | null;
  lastReportedDate: Timestamp | null;
  maturityDate: Timestamp | null;
  memberNumber: string | null;
  monthlyPayment: Numeric | null;
  monthsReviewed: string | null;
  mop: Generated<string | null>;
  notes: string | null;
  openedDate: Timestamp | null;
  organizationId: number | null;
  originalBalance: Numeric | null;
  originalCreditorName: string | null;
  paymentHistoryProfile: string | null;
  paymentPattern: string | null;
  postedDate: Timestamp | null;
  purchasedSoldIndicator: string | null;
  ratingCode: string | null;
  ratingCodeDescription: string | null;
  reportArtifactId: number | null;
  responsibilityCode: string | null;
  scheduledMonthlyPayment: Numeric | null;
  sourceText: string | null;
  status: string | null;
  terms: string | null;
  userId: number | null;
}

export interface TradelineArtifactPresence {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  reportArtifactId: number;
  tradelineId: number;
}

export interface TradelinePaymentHistory {
  accountCondition: string | null;
  complianceConditionCode: string | null;
  consumerInformationIndicator: string | null;
  createdAt: Generated<Timestamp | null>;
  dateOfLastPayment: Timestamp | null;
  ecoaCode: EcoaCode | null;
  id: Generated<number>;
  lastActivityDate: Timestamp | null;
  lastPaymentAmount: Numeric | null;
  lastReportedDate: Timestamp | null;
  minimumPayment: Numeric | null;
  monthlyPayment: Numeric | null;
  paymentPattern: string | null;
  paymentPatternStartDate: Timestamp | null;
  portfolioType: string | null;
  rawSectionText: string | null;
  region: Generated<string>;
  reportArtifactId: number;
  responsibilityCode: Generated<ResponsibilityCode | null>;
  specialCommentCodes: Generated<Json | null>;
  termsFrequency: string | null;
  termsMonths: number | null;
  times120DaysLate: Generated<number | null>;
  times30DaysLate: Generated<number | null>;
  times60DaysLate: Generated<number | null>;
  times90DaysLate: Generated<number | null>;
  tradelineId: number;
  worstDelinquencyCode: string | null;
  worstDelinquencyDate: Timestamp | null;
}

export interface TradelinePaymentHistoryDetail {
  balance: Numeric | null;
  balloonPayment: Numeric | null;
  chargeOff: Numeric | null;
  createdAt: Generated<Timestamp | null>;
  creditLimit: Numeric | null;
  highCredit: Numeric | null;
  id: Generated<number>;
  mop: string | null;
  narrative: string | null;
  pastDue: Numeric | null;
  payment: Numeric | null;
  periodDate: Timestamp | null;
  region: Generated<string>;
  reportArtifactId: number;
  terms: string | null;
  tradelineId: number;
}

export interface TradelineSnapshot {
  accountNumber: string | null;
  accountType: string | null;
  amountPastDue: Numeric | null;
  balance: Numeric | null;
  collectionAgencyName: string | null;
  creditLimit: Numeric | null;
  creditorName: string | null;
  currentBalance: Numeric | null;
  dateClosed: Timestamp | null;
  dateOfFirstDelinquency: Timestamp | null;
  dateOfLastPayment: Timestamp | null;
  ecoaCode: string | null;
  highCredit: Numeric | null;
  id: Generated<number>;
  isCollectionAccount: Generated<boolean | null>;
  lastActivityDate: Timestamp | null;
  lastReportedDate: Timestamp | null;
  mop: string | null;
  openedDate: Timestamp | null;
  originalCreditorName: string | null;
  paymentPattern: string | null;
  reportArtifactId: number | null;
  responsibilityCode: string | null;
  snapshotAt: Generated<Timestamp>;
  status: string | null;
  terms: string | null;
  tradelineId: number;
}

export interface UserAccount {
  addressLine1: string | null;
  addressLine2: string | null;
  city: string | null;
  createdAt: Generated<Timestamp | null>;
  dateOfBirth: Timestamp | null;
  email: string;
  fullName: string | null;
  id: Generated<number>;
  legalNameSignature: string | null;
  phone: string | null;
  postalCode: string | null;
  province: string | null;
  region: Generated<string | null>;
  role: Generated<UserRole | null>;
  termsAcceptedAt: Timestamp | null;
  termsAcceptedVersion: Generated<string | null>;
  userId: number | null;
}

export interface UserPasswords {
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp>;
  displayName: string;
  email: string;
  emailVerified: Generated<boolean>;
  id: Generated<number>;
  organizationId: number | null;
  role: Generated<UserRole>;
}

export interface VersionMigration {
  appliedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  name: string;
  sqlDown: string | null;
  sqlUp: string | null;
  status: Generated<MigrationStatus>;
  versionId: number;
}

export interface DB {
  auditLog: AuditLog;
  bankruptcyRecord: BankruptcyRecord;
  betaIssueReport: BetaIssueReport;
  bureau: Bureau;
  complianceConfig: ComplianceConfig;
  consumerIdentificationDocument: ConsumerIdentificationDocument;
  consumerSignature: ConsumerSignature;
  creditor: Creditor;
  creditorObligationTest: CreditorObligationTest;
  creditorValidationRequirement: CreditorValidationRequirement;
  deadlineEvent: DeadlineEvent;
  disclosureRequirement: DisclosureRequirement;
  discriminationClaim: DiscriminationClaim;
  dynamicScanningRule: DynamicScanningRule;
  emailVerificationTokens: EmailVerificationTokens;
  enforcementMechanism: EnforcementMechanism;
  evidenceAttachment: EvidenceAttachment;
  evidenceEvent: EvidenceEvent;
  featureFlag: FeatureFlag;
  federalGuidance: FederalGuidance;
  identityTheftFreeze: IdentityTheftFreeze;
  industryStandard: IndustryStandard;
  leadReminder: LeadReminder;
  letterTemplate: LetterTemplate;
  licensedCollectionAgency: LicensedCollectionAgency;
  loginAttempts: LoginAttempts;
  metro2ValidationLog: Metro2ValidationLog;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  obligation: Obligation;
  obligationChallengeLog: ObligationChallengeLog;
  obligationInstance: ObligationInstance;
  organizations: Organizations;
  packet: Packet;
  packetComplianceAudit: PacketComplianceAudit;
  packetImpactAssessment: PacketImpactAssessment;
  parserBureauDetectionConfig: ParserBureauDetectionConfig;
  parserFieldMapping: ParserFieldMapping;
  parserKnownEntity: ParserKnownEntity;
  parserMappingVersion: ParserMappingVersion;
  parserRuleCandidate: ParserRuleCandidate;
  parserExtractionRule: ParserExtractionRule;
  parserTestCase: ParserTestCase;
  parserTestRun: ParserTestRun;
  passAEditLog: PassAEditLog;
  passExtraction: PassExtraction;
  passwordResetTokens: PasswordResetTokens;
  postalTransaction: PostalTransaction;
  rateLimitEntry: RateLimitEntry;
  regulatoryNotification: RegulatoryNotification;
  regulatoryUpdateLog: RegulatoryUpdateLog;
  reportArtifact: ReportArtifact;
  reportConsumerInfo: ReportConsumerInfo;
  reportConsumerStatement: ReportConsumerStatement;
  reportCreditScore: ReportCreditScore;
  reportEmploymentInfo: ReportEmploymentInfo;
  reportInquiry: ReportInquiry;
  reportPublicRecord: ReportPublicRecord;
  sessions: Sessions;
  softwareVersion: SoftwareVersion;
  statute: Statute;
  statuteVersion: StatuteVersion;
  subscriptions: Subscriptions;
  successMetric: SuccessMetric;
  supportTicket: SupportTicket;
  supportTicketMessage: SupportTicketMessage;
  suspiciousActivityLog: SuspiciousActivityLog;
  systemSettings: SystemSettings;
  tradeline: Tradeline;
  tradelineArtifactPresence: TradelineArtifactPresence;
  tradelinePaymentHistory: TradelinePaymentHistory;
  tradelinePaymentHistoryDetail: TradelinePaymentHistoryDetail;
  tradelineSnapshot: TradelineSnapshot;
  userAccount: UserAccount;
  userPasswords: UserPasswords;
  users: Users;
  versionMigration: VersionMigration;
  violationCorrection: ViolationCorrection;
  violationCorrectionEvidence: ViolationCorrectionEvidence;
  violationRegulationReference: ViolationRegulationReference;
  violationTrainingExample: ViolationTrainingExample;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const EnforcementMechanismTypeArrayValues: [EnforcementMechanismType, ...EnforcementMechanismType[]] = ["COMPLAINT_PROCEDURE","ENFORCING_BODY","PENALTY"];
export const RegulatoryUpdateStatusArrayValues: [RegulatoryUpdateStatus, ...RegulatoryUpdateStatus[]] = ["APPLIED","ARCHIVED","DETECTED","DISMISSED","UNDER_REVIEW","VERIFIED"];
export const RegulatoryUpdateSourceArrayValues: [RegulatoryUpdateSource, ...RegulatoryUpdateSource[]] = ["AUTOMATED_SCAN","COURT_DECISION","GOVERNMENT_NOTICE","INDUSTRY_BULLETIN","LEGAL_NEWSLETTER","MANUAL_ENTRY"];
export const RegulatoryChangeTypeArrayValues: [RegulatoryChangeType, ...RegulatoryChangeType[]] = ["CASE_LAW","ENFORCEMENT_CHANGE","NEW_REGULATION","NEW_STATUTE","PROCEDURAL_CHANGE","REGULATION_AMENDMENT","STATUTE_AMENDMENT","STATUTE_REPEAL"];
export const CraObligationTypeArrayValues: [CraObligationType, ...CraObligationType[]] = ["ACCURACY_INTEGRITY","CORRECTION_DUTY","DATA_VALIDATION","DISPUTE_INVESTIGATION","DOFD_REPORTING","MONTHLY_REPORTING"];
export const ValidationSeverityArrayValues: [ValidationSeverity, ...ValidationSeverity[]] = ["ERROR","INFO","WARNING"];
export const ObligationStateArrayValues: [ObligationState, ...ObligationState[]] = ["ADDRESSED_VIA_LINKED_DISPUTE","CHALLENGED","INSUFFICIENT_RESPONSE","NO_RESPONSE","OBLIGATION_PENDING","PROCEDURALLY_EXHAUSTED"];
export const AuditActionTypeArrayValues: [AuditActionType, ...AuditActionType[]] = ["BUG_FIX","CHALLENGE_INITIATED","CHALLENGE_UPDATED","CONFIG_UPDATE","CREATE","DATA_EXPORT","DELETE","DOWNLOAD","ESCALATION_TRIGGERED","EXHAUSTION_REACHED","FEATURE_ADDED","FEATURE_REMOVED","LOGIN","LOGIN_FAILED","LOGOUT","PACKET_GENERATED","READ","RESPONSE_RECORDED","SCHEMA_CHANGE","SETTINGS_CHANGED","SYSTEM_CHANGE","UPDATE","UPLOAD"];
export const AuditEntityTypeArrayValues: [AuditEntityType, ...AuditEntityType[]] = ["BUREAU","ENFORCEMENT_MECHANISM","EVIDENCE_EVENT","FURNISHER","FURNISHER_OBLIGATION","FURNISHER_VALIDATION","METRO2_VALIDATION_LOG","OBLIGATION","OBLIGATION_INSTANCE","PACKET","REGULATORY_UPDATE","REPORT_ARTIFACT","STATUTE","SYSTEM","TRADELINE","USER_ACCOUNT"];
export const AuditStatusArrayValues: [AuditStatus, ...AuditStatus[]] = ["FAILURE","SUCCESS"];
export const ObligationSectionArrayValues: [ObligationSection, ...ObligationSection[]] = ["BILL_COLLECTOR","CREDIT_BUREAU","CREDITOR"];
export const BankruptcyTypeArrayValues: [BankruptcyType, ...BankruptcyType[]] = ["BANKRUPTCY_DISCHARGED","BANKRUPTCY_NOT_DISCHARGED","CONSUMER_PROPOSAL","DIVISION_I_PROPOSAL","PERSONAL_BANKRUPTCY"];
export const CanadianProvinceArrayValues: [CanadianProvince, ...CanadianProvince[]] = ["AB","BC","MB","NB","NL","NS","NT","NU","ON","PE","QC","SK","YT"];
export const BankruptcyStatusArrayValues: [BankruptcyStatus, ...BankruptcyStatus[]] = ["ACTIVE","COMPLETED","DISCHARGED","PENDING_REMOVAL","REMOVED"];
export const FreezeTypeArrayValues: [FreezeType, ...FreezeType[]] = ["extended_fraud_alert","fraud_alert","security_freeze"];
export const FreezeStatusArrayValues: [FreezeStatus, ...FreezeStatus[]] = ["active","cancelled","expired","requested","thawed"];
export const SignatureTypeArrayValues: [SignatureType, ...SignatureType[]] = ["document_signing","freeze_authorization","identity_verification","thaw_authorization"];
export const ViolationCategoryArrayValues: [ViolationCategory, ...ViolationCategory[]] = ["ACCOUNT_STATUS_INCONSISTENCY","BALANCE_CALCULATION_VIOLATION","BANKRUPTCY_DISCHARGE_VIOLATION","BUREAU_ACCESS_VIOLATION","BUREAU_DISPUTE_MARKING_FAILURE","BUREAU_INVESTIGATION_FAILURE","BUREAU_NOTIFICATION_FAILURE","BUREAU_REINSERTION_VIOLATION","CLOSED_ACCOUNT_BALANCE_INFLATION","COLLECTION_LIMITATION_EXCEEDED","COLLECTOR_DUPLICATE_REPORTING","COLLECTOR_LICENSE_FAILURE","COLLECTOR_PAYMENT_ACKNOWLEDGMENT_VIOLATION","COLLECTOR_STATUTE_REVIVAL_ATTEMPT","COLLECTOR_UNAUTHORIZED_FEES","CONSENT_WITHDRAWAL_NOT_HONORED","CONSUMER_STATEMENT_SUPPRESSION","CREDIT_LIMIT_MANIPULATION","CREDITOR_RESPONSE_QUALITY","CROSS_BUREAU_INCONSISTENCY","CROSS_ENTITY_DISCREPANCY","DATE_LOGIC_IMPOSSIBLE","DISCLOSURE_DEFICIENCY","DOCUMENTATION_CHAIN_FAILURE","FREEZE_PERIOD_VIOLATION","FURNISHER_AUTHORIZED_USER_MISREPRESENTATION","FURNISHER_JOINT_ACCOUNT_VIOLATION","FURNISHER_POST_DISPUTE_RETALIATION","FURNISHER_REAGING_VIOLATION","FURNISHER_RESPONSE_QUALITY","FURNISHER_STATUS_CODE_MISMATCH","IDENTITY_THEFT_VIOLATION","INVESTIGATION_RUBBER_STAMP","LAST_ACTIVITY_DATE_MANIPULATION","MIXED_FILE_PERSONAL_INFO_MISMATCH","MULTIPLE_COLLECTOR_VIOLATION","PAYMENT_HISTORY_MANIPULATION","PHANTOM_DEBT_UNVERIFIABLE","PROCEDURAL_TIMING_VIOLATION","RESPONSE_ADDRESS_MISMATCH","RESPONSE_INCOMPLETE","RESPONSE_MOV_MISSING","RESPONSE_NO_DOCUMENTATION","RESPONSE_UNAUTHORIZED","RETROACTIVE_HISTORY_MANIPULATION","STALE_REPORTING_FAILURE","STATUTE_APPROACHING","STATUTE_OF_LIMITATIONS","TEMPORAL_MANIPULATION","ZOMBIE_DEBT_RESURRECTION"];
export const KnownEntityTypeArrayValues: [KnownEntityType, ...KnownEntityType[]] = ["account_type","creditor_name","province","remark_code","status_code"];
export const InquiryTypeArrayValues: [InquiryType, ...InquiryType[]] = ["account_review","hard","promotional","soft","unknown"];
export const PublicRecordTypeArrayValues: [PublicRecordType, ...PublicRecordType[]] = ["bankruptcy","civil_judgment","foreclosure","judgment","other","tax_lien","wage_garnishment"];
export const ConsumerStatementTypeArrayValues: [ConsumerStatementType, ...ConsumerStatementType[]] = ["active_duty_alert","dispute","fraud_alert","general_statement","identity_theft","security_freeze"];
export const ResponsibilityCodeArrayValues: [ResponsibilityCode, ...ResponsibilityCode[]] = ["authorized_user","cosigner","individual","joint","on_behalf_of","terminated","unknown"];
export const EcoaCodeArrayValues: [EcoaCode, ...EcoaCode[]] = ["A","B","C","D","E","F","G","H","I","J","K","L","M","N","P","S","T","U","W","X","Z"];
export const ExtractionPassTypeArrayValues: [ExtractionPassType, ...ExtractionPassType[]] = ["A","A_FULL","B"];
export const ExtractionPassStatusArrayValues: [ExtractionPassStatus, ...ExtractionPassStatus[]] = ["completed","failed","pending"];
export const DisclosureCategoryArrayValues: [DisclosureCategory, ...DisclosureCategory[]] = ["CONTENT","IDENTITY","RIGHTS","SOURCES"];
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","support","user"];
export const SubscriptionPlanArrayValues: [SubscriptionPlan, ...SubscriptionPlan[]] = ["annual","beta","monthly"];
export const SubscriptionStatusArrayValues: [SubscriptionStatus, ...SubscriptionStatus[]] = ["active","cancelled","expired","past_due","trialing"];
export const BetaIssueCategoryArrayValues: [BetaIssueCategory, ...BetaIssueCategory[]] = ["BUG","COMPLIANCE","DATA_ISSUE","FEATURE_GAP","OTHER","PERFORMANCE","UI_ISSUE"];
export const BetaIssueStatusArrayValues: [BetaIssueStatus, ...BetaIssueStatus[]] = ["ANALYZED","ANALYZING","DISMISSED","OPEN","RESOLVED"];
export const BetaIssueSeverityArrayValues: [BetaIssueSeverity, ...BetaIssueSeverity[]] = ["CRITICAL","HIGH","LOW","MEDIUM"];
export const PostalTransactionStatusArrayValues: [PostalTransactionStatus, ...PostalTransactionStatus[]] = ["completed","failed","pending","refunded"];
export const DynamicRuleStatusArrayValues: [DynamicRuleStatus, ...DynamicRuleStatus[]] = ["ACTIVE","ARCHIVED","PROPOSED","REJECTED"];
export const VersionStatusArrayValues: [VersionStatus, ...VersionStatus[]] = ["archived","draft","released","staged"];
export const MigrationStatusArrayValues: [MigrationStatus, ...MigrationStatus[]] = ["applied","pending","rolled_back"];
export const FeatureFlagScopeArrayValues: [FeatureFlagScope, ...FeatureFlagScope[]] = ["admin","global","user"];
export const SupportTicketCategoryArrayValues: [SupportTicketCategory, ...SupportTicketCategory[]] = ["ACCOUNT","BILLING","DISPUTE_HELP","OTHER","TECHNICAL"];
export const SupportTicketPriorityArrayValues: [SupportTicketPriority, ...SupportTicketPriority[]] = ["HIGH","LOW","MEDIUM","URGENT"];
export const SupportTicketStatusArrayValues: [SupportTicketStatus, ...SupportTicketStatus[]] = ["CLOSED","IN_PROGRESS","OPEN","RESOLVED","WAITING_ON_USER"];
export const LicenseStatusArrayValues: [LicenseStatus, ...LicenseStatus[]] = ["active","expired","revoked","suspended"];
export const AgencyDataSourceArrayValues: [AgencyDataSource, ...AgencyDataSource[]] = ["admin_manual","ai_verified","ontario_open_data"];
export const ViolationUserStatusArrayValues: [ViolationUserStatus, ...ViolationUserStatus[]] = ["active","dismissed","verified"];
export const PacketProcessingStatusArrayValues: [PacketProcessingStatus, ...PacketProcessingStatus[]] = ["completed","failed","generating","pending","uploading"];
export const LetterTemplateCategoryArrayValues: [LetterTemplateCategory, ...LetterTemplateCategory[]] = ["bureau","provincial","violation_narrative"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
