import { schema, OutputType } from "./create_POST.schema";

import { db } from "../../helpers/db";
import { handleEndpointError } from "../../helpers/endpointErrorHandler";
import { getServerUserSession } from "../../helpers/getServerUserSession";
import { logAudit } from "../../helpers/auditLogger";

export async function handle(request: Request) {
  try {
    const { user } = await getServerUserSession(request);

    // Admin-only endpoint
    if (user.role !== 'admin') {
      return new Response(JSON.stringify({ error: "Forbidden: Admin access required" }), { status: 403 });
    }

    const json = JSON.parse(await request.text());
    const input = schema.parse(json);

    // Create new regulatory update
    // Enforce region = 'CA' per policy
    const newUpdate = await db
      .insertInto("regulatoryUpdateLog")
      .values({
        jurisdiction: input.jurisdiction,
        changeType: input.changeType,
        source: input.source,
        title: input.title,
        description: input.description,
        statutoryReference: input.statutoryReference ?? null,
        effectiveDate: input.effectiveDate ?? null,
        sourceUrl: input.sourceUrl ?? null,
        impactAssessment: input.impactAssessment ?? null,
        actionRequired: input.actionRequired ?? null,
        notes: input.notes ?? null,
        status: input.status ?? "DETECTED", // Default to DETECTED if not provided
        region: "CA",
        // detectedAt is generated by DB default or we can set it to now if needed, 
        // but schema says Generated<Timestamp|null>, usually defaults to now() in DB definition.
        // If we want to be explicit:
        detectedAt: new Date(),
      })
      .returningAll()
      .executeTakeFirstOrThrow();

    console.log(`Created regulatory update: ${newUpdate.id}`);

    await logAudit({
      action: "SYSTEM_CHANGE",
      entityType: "REGULATORY_UPDATE",
      entityId: newUpdate.id,
      userId: user.id,
      details: { title: newUpdate.title, jurisdiction: newUpdate.jurisdiction, status: newUpdate.status },
      status: "SUCCESS",
      request,
    });

    return new Response(JSON.stringify({ update: newUpdate } satisfies OutputType));
  } catch (error) {
    console.error("Error in regulatory-update/create_POST:", error);
    return handleEndpointError(error);
  }
}