import { schema, OutputType } from "./analytics-report_POST.schema";


import { handleEndpointError } from "../../helpers/endpointErrorHandler";
import { getServerUserSession } from "../../helpers/getServerUserSession";
import { generateServerPdf } from "../../helpers/pdfServerUtils";
import { formatPercent } from "../../helpers/formatters";
import type {
  TDocumentDefinitions,
  Content,
  StyleDictionary,
  TableCell,
} from "pdfmake/interfaces";

// Type matching the validated payload exactly
type AnalyticsMetric = {
  label: string;
  total: number;
  successful: number;
  successRate: number;
};

function createMetricTable(title: string, metricsData: AnalyticsMetric[]): Content {
  const headerRow: TableCell[] = [
    { text: "Category", style: "tableHeader" },
    { text: "Total", style: "tableHeader", alignment: "right" },
    { text: "Successful", style: "tableHeader", alignment: "right" },
    { text: "Rate", style: "tableHeader", alignment: "right" },
  ];

  const bodyRows: TableCell[][] = metricsData.map((item) => [
    { text: item.label, style: "tableCell" },
    { text: item.total.toString(), style: "tableCell", alignment: "right" },
    { text: item.successful.toString(), style: "tableCell", alignment: "right" },
    {
      text: formatPercent(item.successRate * 100),
      style: "tableCell",
      alignment: "right",
      color: item.successRate > 0.4 ? "#16a34a" : "#333333",
    },
  ]);

  return [
    { text: title, style: "sectionHeader", margin: [0, 15, 0, 5] },
    {
      table: {
        headerRows: 1,
        widths: ["*", "auto", "auto", "auto"],
        body: [headerRow, ...bodyRows],
      },
      layout: "lightHorizontalLines",
    },
  ];
}

export async function handle(request: Request) {
  try {
    // Authenticate the user
    await getServerUserSession(request);

    // Parse and validate the input
    const json = JSON.parse(await request.text());
    const config = schema.parse(json);

    const { data, title = "Success Analytics Report" } = config;
    const dateStr = new Date().toLocaleDateString("en-CA");

    const content: Content[] = [];

    // Title
    content.push({ text: title, style: "reportTitle", margin: [0, 0, 0, 20] });

    // Overall Stats Grid
    content.push({
      text: "Overall Performance",
      style: "sectionHeader",
      margin: [0, 0, 0, 10],
    });

    content.push({
      columns: [
        {
          stack: [
            { text: "Success Rate", style: "metricLabel" },
            {
              text: formatPercent(data.overall.successRate * 100),
              style: "metricValueSuccess",
            },
          ],
        },
        {
          stack: [
            { text: "Total Disputes", style: "metricLabel" },
            { text: data.overall.totalDisputes.toString(), style: "metricValue" },
          ],
        },
        {
          stack: [
            { text: "Active", style: "metricLabel" },
            { text: data.overall.activeDisputes.toString(), style: "metricValue" },
          ],
        },
        {
          stack: [
            { text: "Avg Resolution", style: "metricLabel" },
            {
              text: `${data.overall.averageResolutionTimeDays} days`,
              style: "metricValue",
            },
          ],
        },
      ],
      columnGap: 10,
      margin: [0, 0, 0, 20],
    });

    // Breakdown Sections
    content.push(createMetricTable("Performance by Dispute Vector", data.byVector));
    content.push(createMetricTable("Performance by Violation", data.byViolation));
    content.push(createMetricTable("Creditor Performance", data.byCreditor));
    content.push(createMetricTable("Bureau Performance", data.byBureau));

    const styles: StyleDictionary = {
      reportTitle: { fontSize: 22, bold: true, color: "#111827" },
      sectionHeader: { fontSize: 14, bold: true, color: "#374151" },
      tableHeader: {
        bold: true,
        fontSize: 10,
        color: "#111827",
        fillColor: "#f3f4f6",
      },
      tableCell: { fontSize: 10, color: "#4b5563" },
      metricLabel: { fontSize: 10, color: "#6b7280" },
      metricValue: { fontSize: 18, bold: true, color: "#111827" },
      metricValueSuccess: { fontSize: 18, bold: true, color: "#16a34a" },
      footer: { fontSize: 8, color: "#9ca3af", italics: true },
    };

    const docDefinition: TDocumentDefinitions = {
      content,
      styles,
      defaultStyle: { font: "Roboto" },
      pageSize: "LETTER",
      pageMargins: [40, 40, 40, 60],
      footer: (currentPage, pageCount) => ({
        columns: [
          { text: `Generated by Floot on ${dateStr}`, alignment: "left", style: "footer" },
          { text: `Page ${currentPage} of ${pageCount}`, alignment: "right", style: "footer" },
        ],
        margin: [40, 20, 40, 0],
      }),
    };

    const pdfBase64 = await generateServerPdf(docDefinition);

    return new Response(
      JSON.stringify({ pdf: pdfBase64 } satisfies OutputType),
      {
        headers: { "Content-Type": "application/json" },
      }
    );
  } catch (error) {
    return handleEndpointError(error);
  }
}