import { schema, OutputType } from "./rescan-compliance_POST.schema";
import { getServerUserSession } from "../../helpers/getServerUserSession";
import { db } from "../../helpers/db";
import { handleEndpointError, OriginNotAllowedError } from "../../helpers/endpointErrorHandler";
import { validateOrigin } from "../../helpers/domainGuard";
import { scanForViolations, mapViolationToObligationType, getAdminReviewedStatutoryBasis } from "../../helpers/complianceScanner";
import { normalizeDetectedViolations } from "../../helpers/complianceFindingNormalizer";
import { getDeterministicViolationStatutoryBasis } from "../../helpers/violationRuleEvidence";
import { evaluateViolationPacketConfidenceGate } from "../../helpers/violationPacketConfidenceGate";

import type { ViolationCategory } from "../../helpers/schema";

export async function handle(request: Request) {
  try {
    // 1. Authenticate user
    const { user } = await getServerUserSession(request);

    const guardResult = await validateOrigin(request);
    if (!guardResult.valid && guardResult.mode === "enforce") {
      throw new OriginNotAllowedError();
    }

    // 2. Parse input
    const json = JSON.parse(await request.text());
    const input = schema.parse(json);

    // 3. Verify tradeline ownership with three-tier access control
    const tradeline = await db
      .selectFrom("tradeline")
      .select(["id", "userId", "organizationId"])
      .where("id", "=", input.tradelineId)
      .executeTakeFirst();

    if (!tradeline) {
      return new Response(
        JSON.stringify({ error: "Tradeline not found" }),
        { status: 404 }
      );
    }

    // Access control: admin can access all tradelines, non-admin can only access their own
    if (user.role !== "admin" && tradeline.userId !== user.id) {
      return new Response(
        JSON.stringify({ error: "Access denied: this tradeline does not belong to you." }),
        { status: 403 }
      );
    }

    const preservedViolations = await db
      .selectFrom("creditorObligationTest")
      .select(["violationCategory", "userExplanation"])
      .where("tradelineId", "=", input.tradelineId)
      .where("userStatus", "!=", "active")
      .execute();

    const preservedSignatures = new Set(
      preservedViolations.map((v) => `${v.violationCategory}|${v.userExplanation}`)
    );

    // 4. Before deleting old violations, capture packets that reference them so we can re-link them.
    //    We build a map of: violationCategory -> packetIds[]
    const packetsLinkedToOldViolations = await db
      .selectFrom("packet")
      .innerJoin(
        "creditorObligationTest",
        "packet.creditorObligationTestId",
        "creditorObligationTest.id"
      )
      .select([
        "packet.id as packetId",
        "creditorObligationTest.violationCategory",
      ])
      .where("creditorObligationTest.tradelineId", "=", input.tradelineId)
      .where("creditorObligationTest.autoGenerated", "=", true)
      .where("creditorObligationTest.userStatus", "=", "active")
      .execute();

    // Build category → packetIds map
    const categoryToPacketIds = new Map<ViolationCategory, number[]>();
    for (const row of packetsLinkedToOldViolations) {
      if (row.violationCategory === null) continue;
      const category = row.violationCategory as ViolationCategory;
      const existing = categoryToPacketIds.get(category) ?? [];
      existing.push(row.packetId);
      categoryToPacketIds.set(category, existing);
    }

    console.log(
      `Found ${packetsLinkedToOldViolations.length} packets linked to auto-generated violations for tradeline ${input.tradelineId}`
    );

    // 5. Delete all existing auto-generated violations for this tradeline.
    //    Manually created violations (autoGenerated = false or null) are preserved.
    const deleteResult = await db
      .deleteFrom("creditorObligationTest")
      .where("tradelineId", "=", input.tradelineId)
      .where("autoGenerated", "=", true)
      .where("userStatus", "=", "active")
      .execute();

    console.log(
      `Deleted ${deleteResult[0]?.numDeletedRows ?? 0} existing auto-generated violations for tradeline ${input.tradelineId}`
    );

    console.log(
      `Dispute workflow instance mutation is reset; preserved existing obligation instances for tradeline ${input.tradelineId}`
    );

    // 6. Run the compliance scan
    const detectedViolations = normalizeDetectedViolations(
      await scanForViolations(input.tradelineId)
    );

    console.log(`Detected ${detectedViolations.length} violations from scan`);

    // 7. Insert all detected compliance findings fresh and re-link historical packets by violation category.
    //    Dispute workflow instance creation is reset pending the new dispute-process architecture.
    const insertedIds: number[] = [];
    let totalRelinkedPackets = 0;

    for (const violation of detectedViolations) {
      try {
        const signature = `${violation.violationCategory}|${violation.userExplanation}`;
        if (preservedSignatures.has(signature)) {
          console.log(`Skipping insertion for preserved violation: ${signature}`);
          continue;
        }

        const technicalDetails = JSON.parse(JSON.stringify({
          ...violation.technicalDetails,
          responsibleEntity: violation.responsibleEntity || null,
        }));
        const packetConfidenceGate = evaluateViolationPacketConfidenceGate({
          technicalDetails,
          userStatus: "active",
        });
        const validationStatus =
          packetConfidenceGate.blockerCode === "parser_uncertain"
            ? "PARSER_UNCERTAIN"
            : packetConfidenceGate.blockerCode === "violation_needs_review"
              ? "NEEDS_USER_REVIEW"
              : "PENDING";

        const result = await db
          .insertInto("creditorObligationTest")
          .values({
            tradelineId: input.tradelineId,
            obligationType: violation.violationCategory
              ? mapViolationToObligationType(violation.violationCategory)
              : "ACCURACY_INTEGRITY",
            violationCategory: violation.violationCategory,
            severity: violation.severity,
            confidenceScore: violation.confidenceScore,
            userExplanation: violation.userExplanation,
            technicalDetails,
            recommendedAction: violation.recommendedAction,
            statutoryBasis:
              getAdminReviewedStatutoryBasis(violation) ??
              getDeterministicViolationStatutoryBasis(violation),
            detectedAt: new Date(),
            validationStatus,
            obligationState: "OBLIGATION_PENDING",
            autoGenerated: true,
          })
          .returning("id")
          .executeTakeFirst();

        if (result?.id) {
          const newViolationId = Number(result.id);
          insertedIds.push(newViolationId);

          console.log(
            packetConfidenceGate.packetReady
              ? `Dispute workflow instance creation is reset; persisted violation #${newViolationId} without creating an obligation instance.`
              : `Persisted violation #${newViolationId} with review gate: ${packetConfidenceGate.message}`
          );

          // Re-link any packets that were previously associated with an old violation
          // of the same violation category
          if (
            violation.violationCategory &&
            categoryToPacketIds.has(violation.violationCategory)
          ) {
            const packetIds = categoryToPacketIds.get(violation.violationCategory)!;

            const updateResult = await db
              .updateTable("packet")
              .set({ creditorObligationTestId: newViolationId })
              .where("id", "in", packetIds)
              .execute();

            const relinkedCount = Number(updateResult[0]?.numUpdatedRows ?? 0);
            totalRelinkedPackets += relinkedCount;

            console.log(
              `Re-linked ${relinkedCount} packet(s) to new violation ID ${newViolationId} (category: ${violation.violationCategory})`
            );

            // Remove the category from the map so we don't double-link if somehow
            // there are multiple new violations with the same category
            categoryToPacketIds.delete(violation.violationCategory);
          }
        }
      } catch (error) {
        console.error(`Failed to persist violation:`, error);
      }
    }

    console.log(
      `Persisted ${insertedIds.length} violations. Dispute workflow instance creation is reset. Re-linked ${totalRelinkedPackets} packet(s) across all categories.`
    );

    // 8. Log the action
    await db
      .insertInto("auditLog")
      .values({
        actionType: "UPDATE",
        entityType: "TRADELINE",
        entityId: input.tradelineId,
        userId: user.id,
        details: {
          action: "manual_compliance_rescan",
          totalDetected: detectedViolations.length,
          inserted: insertedIds.length,
          obligationInstancesCreated: 0,
          packetsRelinked: totalRelinkedPackets,
        } as any,
        status: "SUCCESS",
        timestamp: new Date(),
        ipAddress: request.headers.get("x-forwarded-for") || "unknown",
        userAgent: request.headers.get("user-agent"),
      })
      .execute();

    const output: OutputType = {
      ok: true,
      violationsFound: detectedViolations.length,
      message: `Rescan complete. Found ${detectedViolations.length} total issues. ${insertedIds.length} were successfully recorded. Dispute workflow instance creation is reset. ${totalRelinkedPackets} packet(s) were re-linked to updated violations.`,
    };

    return new Response(JSON.stringify(output));
  } catch (error) {
    console.error("Error in rescan-compliance:", error);
    return handleEndpointError(error);
  }
}

