import "../loadEnv.js";

import assert from "node:assert/strict";
import { db } from "../helpers/db";
import { ensureViolationCorrectionSchema } from "../helpers/violationCorrectionSchema";
import { finalizeCorrection } from "../helpers/violationCorrectionManager";

const LOCAL_HOSTS = new Set(["localhost", "127.0.0.1", "::1"]);

function requireLocalDatabaseUrl(): string {
  const url = process.env.FLOOT_DATABASE_URL;
  if (!url) {
    throw new Error("FLOOT_DATABASE_URL is not set.");
  }

  if (process.env.CRP_LOCAL_DEV !== "true") {
    throw new Error("Refusing DB integration test unless CRP_LOCAL_DEV=true.");
  }

  const parsed = new URL(url);
  if (!LOCAL_HOSTS.has(parsed.hostname)) {
    throw new Error(`Refusing DB integration test against non-local database host: ${parsed.hostname}`);
  }

  return url;
}

async function main() {
  requireLocalDatabaseUrl();
  await ensureViolationCorrectionSchema();

  const marker = `violation-correction-test-${Date.now()}`;
  const ids = {
    userId: null as number | null,
    bureauId: null as number | null,
    creditorId: null as number | null,
    artifactId: null as number | null,
    runId: null as number | null,
    tradelineId: null as number | null,
    violationId: null as number | null,
    correctionIds: [] as number[],
  };

  try {
    const now = new Date();
    const user = await db
      .insertInto("users")
      .values({
        email: `${marker}@example.test`,
        displayName: "Violation Correction Test Admin",
        role: "admin",
        emailVerified: true,
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.userId = user.id;

    const bureau = await db
      .insertInto("bureau")
      .values({
        name: `Test Bureau ${marker}`,
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.bureauId = bureau.id;

    const creditor = await db
      .insertInto("creditor")
      .values({
        name: `Test Creditor ${marker}`,
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.creditorId = creditor.id;

    const artifact = await db
      .insertInto("reportArtifact")
      .values({
        userId: user.id,
        artifactType: "integration_test",
        processingStatus: "completed",
        data: { marker },
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.artifactId = artifact.id;

    const run = await db
      .insertInto("passExtraction")
      .values({
        reportArtifactId: artifact.id,
        pass: "A",
        status: "completed",
        rawEvidence: { marker },
        startedAt: now,
        completedAt: now,
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.runId = run.id;

    const tradeline = await db
      .insertInto("tradeline")
      .values({
        userId: user.id,
        bureauId: bureau.id,
        creditorId: creditor.id,
        reportArtifactId: artifact.id,
        accountNumber: marker,
        accountType: "integration",
        status: "Open",
        sourceText: "Balance field shows 200 while extracted balance shows 100.",
        createdAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.tradelineId = tradeline.id;

    const originalViolation = await db
      .insertInto("creditorObligationTest")
      .values({
        tradelineId: tradeline.id,
        creditorId: creditor.id,
        obligationType: "ACCURACY_INTEGRITY",
        violationCategory: "DOCUMENTATION_CHAIN_FAILURE",
        severity: "WARNING",
        confidenceScore: 63,
        userExplanation: "Original machine output should remain unchanged.",
        technicalDetails: { marker, fieldName: "balance" },
        recommendedAction: "Review source documentation.",
        validationStatus: "PENDING",
        obligationState: "OBLIGATION_PENDING",
        autoGenerated: true,
        detectedAt: now,
        createdAt: now,
        updatedAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.violationId = originalViolation.id;

    const corrected = await db
      .insertInto("violationCorrection")
      .values({
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        originalViolationId: originalViolation.id,
        correctionAction: "corrected",
        correctedViolationType: "BALANCE_CALCULATION_VIOLATION",
        correctedSummary: "Potential balance inconsistency requires review.",
        correctedExplanation: "The reported and extracted balance fields do not match.",
        correctedSeverity: "WARNING",
        correctedConfidence: 91,
        correctionReason: "Machine output classified the wrong issue type.",
        adminNotes: "Integration test correction.",
        status: "in_review",
        trainingLabel: "misclassified",
        trainingNoteOnly: false,
        useForTraining: true,
        createdByAdminId: user.id,
        createdAt: now,
        updatedAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.correctionIds.push(corrected.id);

    await db
      .insertInto("violationCorrectionEvidence")
      .values({
        correctionId: corrected.id,
        sourceDocumentId: artifact.id,
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        pageNumber: 1,
        fieldName: "balance",
        textExcerpt: "Balance field shows 200 while extracted balance shows 100.",
        normalizedValue: "200 vs 100",
        evidenceReason: "Supports the corrected balance issue classification.",
        adminSelected: true,
        createdAt: now,
      })
      .execute();

    await db
      .insertInto("violationRegulationReference")
      .values({
        violationId: originalViolation.id,
        correctionId: corrected.id,
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        jurisdiction: "federal",
        country: "Canada",
        regulatorOrStandardBody: "Federal privacy framework",
        regulationName: "PIPEDA",
        statuteOrRuleName: "Accuracy principle",
        sectionNumber: "Schedule 1, Principle 4.6",
        regulationTextExcerpt: "Information should be accurate, complete, and up to date for its purpose.",
        citationSource: "Integration test registry",
        citationConfidence: 0.8,
        adminVerifiedCitation: true,
        mappingStatus: "active",
        createdAt: now,
        updatedAt: now,
      })
      .execute();

    const finalized = await finalizeCorrection(corrected.id, user.id);
    assert.equal(finalized.correction.status, "finalized");
    assert.equal(finalized.trainingExample.label, "misclassified");

    const unchangedOriginal = await db
      .selectFrom("creditorObligationTest")
      .select(["violationCategory", "userExplanation"])
      .where("id", "=", originalViolation.id)
      .executeTakeFirstOrThrow();
    assert.equal(unchangedOriginal.violationCategory, "DOCUMENTATION_CHAIN_FAILURE");
    assert.equal(unchangedOriginal.userExplanation, "Original machine output should remain unchanged.");

    const rejected = await db
      .insertInto("violationCorrection")
      .values({
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        originalViolationId: originalViolation.id,
        correctionAction: "rejected",
        correctedViolationType: "DOCUMENTATION_CHAIN_FAILURE",
        correctedSummary: "Machine output is not relevant to this account.",
        correctedSeverity: "INFO",
        correctionReason: "Evidence does not support this issue.",
        status: "in_review",
        trainingLabel: "false_positive",
        createdByAdminId: user.id,
        createdAt: now,
        updatedAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.correctionIds.push(rejected.id);

    await db
      .insertInto("violationCorrectionEvidence")
      .values({
        correctionId: rejected.id,
        sourceDocumentId: artifact.id,
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        pageNumber: 1,
        textExcerpt: "No collection assignment date is shown in this temporary fixture.",
        evidenceReason: "Supports rejecting the machine output.",
        createdAt: now,
      })
      .execute();

    const finalizedRejected = await finalizeCorrection(rejected.id, user.id);
    assert.equal(finalizedRejected.trainingExample.label, "false_positive");

    const incomplete = await db
      .insertInto("violationCorrection")
      .values({
        extractionRunId: run.id,
        tradelineId: tradeline.id,
        correctionAction: "corrected",
        correctedViolationType: "BALANCE_CALCULATION_VIOLATION",
        status: "in_review",
        createdByAdminId: user.id,
        createdAt: now,
        updatedAt: now,
      })
      .returning("id")
      .executeTakeFirstOrThrow();
    ids.correctionIds.push(incomplete.id);

    await assert.rejects(() => finalizeCorrection(incomplete.id, user.id), /evidence/i);

    const trainingCount = await db
      .selectFrom("violationTrainingExample")
      .select((eb) => eb.fn.countAll<string>().as("count"))
      .where("correctionId", "in", ids.correctionIds)
      .executeTakeFirstOrThrow();
    assert.equal(Number(trainingCount.count), 2);

    console.log("Violation correction DB integration checks passed.");
  } finally {
    if (ids.correctionIds.length > 0) {
      await db.deleteFrom("violationTrainingExample").where("correctionId", "in", ids.correctionIds).execute();
      await db.deleteFrom("violationRegulationReference").where("correctionId", "in", ids.correctionIds).execute();
      await db.deleteFrom("violationCorrectionEvidence").where("correctionId", "in", ids.correctionIds).execute();
      await db.deleteFrom("violationCorrection").where("id", "in", ids.correctionIds).execute();
    }
    if (ids.violationId) await db.deleteFrom("creditorObligationTest").where("id", "=", ids.violationId).execute();
    if (ids.tradelineId) await db.deleteFrom("tradeline").where("id", "=", ids.tradelineId).execute();
    if (ids.runId) await db.deleteFrom("passExtraction").where("id", "=", ids.runId).execute();
    if (ids.artifactId) await db.deleteFrom("reportArtifact").where("id", "=", ids.artifactId).execute();
    if (ids.creditorId) await db.deleteFrom("creditor").where("id", "=", ids.creditorId).execute();
    if (ids.bureauId) await db.deleteFrom("bureau").where("id", "=", ids.bureauId).execute();
    if (ids.userId) {
      await db.deleteFrom("auditLog").where("userId", "=", ids.userId).execute();
      await db.deleteFrom("users").where("id", "=", ids.userId).execute();
    }
    await db.destroy();
  }
}

main().catch(async (error) => {
  console.error(error instanceof Error ? error.message : String(error));
  try {
    await db.destroy();
  } catch {
    // ignore shutdown errors
  }
  process.exit(1);
});
