import { schema, OutputType } from "./list_GET.schema";

import { db } from "../../helpers/db";
import { handleEndpointError } from "../../helpers/endpointErrorHandler";
import { getServerUserSession } from "../../helpers/getServerUserSession";
import { shouldSuppressStaleReportingViolation } from "../../helpers/staleReportingGuard";
import { sql } from "kysely";

export async function handle(request: Request) {
  try {
    const { user } = await getServerUserSession(request);

    const url = new URL(request.url);
    const queryParams = {
      creditorId: url.searchParams.get('creditorId') ? Number(url.searchParams.get('creditorId')) : undefined,
      obligationState: url.searchParams.get('obligationState') || undefined,
      tradelineId: url.searchParams.get('tradelineId') ? Number(url.searchParams.get('tradelineId')) : undefined,
      limit: url.searchParams.get('limit') ?? undefined,
      offset: url.searchParams.get('offset') ?? undefined,
    };

    const input = schema.parse(queryParams);

    const buildBaseQuery = () =>
      db
        .selectFrom('creditorObligationTest')
        .leftJoin('creditor', 'creditor.id', 'creditorObligationTest.creditorId')
        .leftJoin('tradeline', 'tradeline.id', 'creditorObligationTest.tradelineId')
        .leftJoin('creditor as tradelineCreditor', 'tradelineCreditor.id', 'tradeline.creditorId')
        .leftJoin('bureau', 'bureau.id', 'tradeline.bureauId')
        // Only return records with valid tradelineId (exclude orphaned records)
        .where('creditorObligationTest.tradelineId', 'is not', null);

    const applyFilters = <T extends ReturnType<typeof buildBaseQuery>>(q: T): T => {
      let filtered = q;
      if (input.creditorId !== undefined) {
        filtered = filtered.where('creditorObligationTest.creditorId', '=', input.creditorId) as T;
      }
      if (input.obligationState !== undefined) {
        filtered = filtered.where('creditorObligationTest.obligationState', '=', input.obligationState as any) as T;
      }
      if (input.tradelineId !== undefined) {
        filtered = filtered.where('creditorObligationTest.tradelineId', '=', input.tradelineId) as T;
      }
      if (user.role !== 'admin') {
        filtered = filtered.where('tradeline.userId', '=', user.id) as T;
      }
      return filtered;
    };

    const shouldSuppressStaleForRow = (row: {
      violationCategory: string | null;
      tradelineStatus: string | null;
      tradelineDateClosed: Date | string | null;
      tradelineDatePaidSettled: Date | string | null;
      tradelineIsCollectionAccount: boolean | null;
      tradelineCollectionAgencyName: string | null;
      tradelineAccountType: string | null;
    }): boolean =>
      shouldSuppressStaleReportingViolation(row.violationCategory, {
        status: row.tradelineStatus,
        dateClosed: row.tradelineDateClosed,
        datePaidSettled: row.tradelineDatePaidSettled,
        isCollectionAccount: row.tradelineIsCollectionAccount,
        collectionAgencyName: row.tradelineCollectionAgencyName,
        accountType: row.tradelineAccountType,
      });

    // Count query (count only rows that remain after stale suppression)
    const countRows = await applyFilters(
      buildBaseQuery().select([
        "creditorObligationTest.violationCategory",
        "tradeline.status as tradelineStatus",
        "tradeline.dateClosed as tradelineDateClosed",
        "tradeline.datePaidSettled as tradelineDatePaidSettled",
        "tradeline.isCollectionAccount as tradelineIsCollectionAccount",
        "tradeline.collectionAgencyName as tradelineCollectionAgencyName",
        "tradeline.accountType as tradelineAccountType",
      ])
    ).execute();
    const total = countRows.filter((row) => !shouldSuppressStaleForRow(row)).length;

    // Data query
    let dataQuery = applyFilters(
      buildBaseQuery().select([
        'creditorObligationTest.id',
        'creditorObligationTest.creditorId',
        'creditorObligationTest.obligationType',
        'creditorObligationTest.obligationState',
        'creditorObligationTest.obligationSequence',
        'creditorObligationTest.disputeVector',
        'creditorObligationTest.lastChallengeDate',
        'creditorObligationTest.responseDeadline',
        'creditorObligationTest.responsesReceived',
        'creditorObligationTest.metro2Version',
        'creditorObligationTest.statutoryBasis',
        'creditorObligationTest.severity',
        'creditorObligationTest.omissions',
        'creditorObligationTest.validationStatus',
        'creditorObligationTest.escalationPath',
        'creditorObligationTest.notes',
        'creditorObligationTest.lastTestDate',
        'creditorObligationTest.tradelineId',
        'creditorObligationTest.createdAt',
        'creditorObligationTest.updatedAt',
        'creditorObligationTest.violationCategory',
        'creditorObligationTest.confidenceScore',
        'creditorObligationTest.autoGenerated',
        'creditorObligationTest.userExplanation',
        'creditorObligationTest.technicalDetails',
        'creditorObligationTest.recommendedAction',
        'creditorObligationTest.detectedAt',
        'creditorObligationTest.userStatus',
        'creditorObligationTest.userStatusReason',
        'creditorObligationTest.userStatusUpdatedAt',
        sql<string | null>`coalesce("creditor"."name", "tradelineCreditor"."name")`.as('creditorName'),
        'tradeline.accountNumber as tradelineAccountNumber',
        'tradeline.status as tradelineDisplayStatus',
        'tradeline.currentBalance as tradelineCurrentBalance',
        'tradeline.balance as tradelineBalance',
        'bureau.name as tradelineBureauName',
        "tradeline.status as tradelineStatus",
        "tradeline.dateClosed as tradelineDateClosed",
        "tradeline.datePaidSettled as tradelineDatePaidSettled",
        "tradeline.isCollectionAccount as tradelineIsCollectionAccount",
        "tradeline.collectionAgencyName as tradelineCollectionAgencyName",
        "tradeline.accountType as tradelineAccountType",
      ])
    )
      .orderBy('creditorObligationTest.detectedAt', 'desc')
      .orderBy('creditorObligationTest.createdAt', 'desc');

    if (input.limit !== undefined) {
      dataQuery = dataQuery.limit(input.limit);
      if (input.offset !== undefined) {
        dataQuery = dataQuery.offset(input.offset);
      }
    }

    const obligationTests = (await dataQuery.execute()).filter(
      (row) => !shouldSuppressStaleForRow(row)
    );

    // Province enrichment: for any test missing province in technicalDetails,
    // look it up from report_consumer_info via the tradeline's report_artifact_id.
    const tradelineIdsNeedingProvince = [
      ...new Set(
        obligationTests
          .filter((t) => {
            const td = t.technicalDetails as Record<string, unknown> | null;
            return t.tradelineId !== null && (!td || !td['province']);
          })
          .map((t) => t.tradelineId as number)
      ),
    ];

    const tradelineProvinceMap = new Map<number, string>();

    if (tradelineIdsNeedingProvince.length > 0) {
      const provinceRows = await db
        .selectFrom('tradeline')
        .innerJoin(
          'reportConsumerInfo',
          'reportConsumerInfo.reportArtifactId',
          'tradeline.reportArtifactId'
        )
        .select(['tradeline.id as tradelineId', 'reportConsumerInfo.province'])
        .where('tradeline.id', 'in', tradelineIdsNeedingProvince)
        .where('reportConsumerInfo.province', 'is not', null)
        .where('tradeline.reportArtifactId', 'is not', null)
        .execute();

      for (const row of provinceRows) {
        if (row.province && !tradelineProvinceMap.has(row.tradelineId)) {
          tradelineProvinceMap.set(row.tradelineId, row.province);
        }
      }

      console.log(`Province enrichment: resolved province for ${tradelineProvinceMap.size} of ${tradelineIdsNeedingProvince.length} tradelines needing enrichment`);
    }

    // Apply enriched provinces to technicalDetails only when a real province was found.
    const enrichedObligationTests = obligationTests.map((test) => {
      const td = test.technicalDetails as Record<string, unknown> | null;
      if (test.tradelineId !== null && (!td || !td['province'])) {
        const province = tradelineProvinceMap.get(test.tradelineId as number);
        if (province) {
          return {
            ...test,
            technicalDetails: { ...(td ?? {}), province },
          };
        }
      }
      return test;
    });

    const responseObligationTests = enrichedObligationTests.map((test) => {
      const {
        tradelineStatus,
        tradelineDateClosed,
        tradelineDatePaidSettled,
        tradelineIsCollectionAccount,
        tradelineCollectionAgencyName,
        tradelineAccountType,
        ...rest
      } = test as any;
      return rest;
    });

    return new Response(JSON.stringify({ obligationTests: responseObligationTests as any, total } satisfies OutputType));
  } catch (error) {
    console.error("Error listing creditor obligation tests:", error);
    return handleEndpointError(error);
  }
}
