import { schema, OutputType } from "./list_GET.schema";

import { db } from "../../helpers/db";
import { handleEndpointError } from "../../helpers/endpointErrorHandler";
import { getServerUserSession } from "../../helpers/getServerUserSession";

export async function handle(request: Request) {
  try {
    const { user } = await getServerUserSession(request);

    const url = new URL(request.url);
    const queryParams = {
      creditorId: url.searchParams.get('creditorId') ? Number(url.searchParams.get('creditorId')) : undefined,
      obligationState: url.searchParams.get('obligationState') || undefined,
      tradelineId: url.searchParams.get('tradelineId') ? Number(url.searchParams.get('tradelineId')) : undefined,
      limit: url.searchParams.get('limit') ?? undefined,
      offset: url.searchParams.get('offset') ?? undefined,
    };

    const input = schema.parse(queryParams);

    const buildBaseQuery = () =>
      db
        .selectFrom('creditorObligationTest')
        .leftJoin('creditor', 'creditor.id', 'creditorObligationTest.creditorId')
        .leftJoin('tradeline', 'tradeline.id', 'creditorObligationTest.tradelineId')
        // Only return records with valid tradelineId (exclude orphaned records)
        .where('creditorObligationTest.tradelineId', 'is not', null);

    const applyFilters = <T extends ReturnType<typeof buildBaseQuery>>(q: T): T => {
      let filtered = q;
      if (input.creditorId !== undefined) {
        filtered = filtered.where('creditorObligationTest.creditorId', '=', input.creditorId) as T;
      }
      if (input.obligationState !== undefined) {
        filtered = filtered.where('creditorObligationTest.obligationState', '=', input.obligationState as any) as T;
      }
      if (input.tradelineId !== undefined) {
        filtered = filtered.where('creditorObligationTest.tradelineId', '=', input.tradelineId) as T;
      }
      if (user.role !== 'admin') {
        filtered = filtered.where('tradeline.userId', '=', user.id) as T;
      }
      return filtered;
    };

    // Count query
    const countResult = await applyFilters(
      buildBaseQuery().select((eb) => eb.fn.countAll<string>().as('total'))
    ).executeTakeFirstOrThrow();
    const total = parseInt(countResult.total, 10);

    // Data query
    let dataQuery = applyFilters(
      buildBaseQuery().select([
        'creditorObligationTest.id',
        'creditorObligationTest.creditorId',
        'creditorObligationTest.obligationType',
        'creditorObligationTest.obligationState',
        'creditorObligationTest.obligationSequence',
        'creditorObligationTest.disputeVector',
        'creditorObligationTest.lastChallengeDate',
        'creditorObligationTest.responseDeadline',
        'creditorObligationTest.responsesReceived',
        'creditorObligationTest.metro2Version',
        'creditorObligationTest.statutoryBasis',
        'creditorObligationTest.severity',
        'creditorObligationTest.omissions',
        'creditorObligationTest.validationStatus',
        'creditorObligationTest.escalationPath',
        'creditorObligationTest.notes',
        'creditorObligationTest.lastTestDate',
        'creditorObligationTest.tradelineId',
        'creditorObligationTest.createdAt',
        'creditorObligationTest.updatedAt',
        'creditorObligationTest.violationCategory',
        'creditorObligationTest.confidenceScore',
        'creditorObligationTest.autoGenerated',
        'creditorObligationTest.userExplanation',
        'creditorObligationTest.technicalDetails',
        'creditorObligationTest.recommendedAction',
        'creditorObligationTest.detectedAt',
        'creditorObligationTest.userStatus',
        'creditorObligationTest.userStatusReason',
        'creditorObligationTest.userStatusUpdatedAt',
        'creditor.name as creditorName',
      ])
    )
      .orderBy('creditorObligationTest.detectedAt', 'desc')
      .orderBy('creditorObligationTest.createdAt', 'desc');

    if (input.limit !== undefined) {
      dataQuery = dataQuery.limit(input.limit);
      if (input.offset !== undefined) {
        dataQuery = dataQuery.offset(input.offset);
      }
    }

    const obligationTests = await dataQuery.execute();

    // Province enrichment: for any test missing province in technicalDetails,
    // look it up from report_consumer_info via the tradeline's report_artifact_id.
    const tradelineIdsNeedingProvince = [
      ...new Set(
        obligationTests
          .filter((t) => {
            const td = t.technicalDetails as Record<string, unknown> | null;
            return t.tradelineId !== null && (!td || !td['province']);
          })
          .map((t) => t.tradelineId as number)
      ),
    ];

    const tradelineProvinceMap = new Map<number, string>();

    if (tradelineIdsNeedingProvince.length > 0) {
      const provinceRows = await db
        .selectFrom('tradeline')
        .innerJoin(
          'reportConsumerInfo',
          'reportConsumerInfo.reportArtifactId',
          'tradeline.reportArtifactId'
        )
        .select(['tradeline.id as tradelineId', 'reportConsumerInfo.province'])
        .where('tradeline.id', 'in', tradelineIdsNeedingProvince)
        .where('reportConsumerInfo.province', 'is not', null)
        .where('tradeline.reportArtifactId', 'is not', null)
        .execute();

      for (const row of provinceRows) {
        if (row.province && !tradelineProvinceMap.has(row.tradelineId)) {
          tradelineProvinceMap.set(row.tradelineId, row.province);
        }
      }

      console.log(`Province enrichment: resolved province for ${tradelineProvinceMap.size} of ${tradelineIdsNeedingProvince.length} tradelines needing enrichment`);
    }

    // Apply enriched provinces to technicalDetails only when a real province was found.
    const enrichedObligationTests = obligationTests.map((test) => {
      const td = test.technicalDetails as Record<string, unknown> | null;
      if (test.tradelineId !== null && (!td || !td['province'])) {
        const province = tradelineProvinceMap.get(test.tradelineId as number);
        if (province) {
          return {
            ...test,
            technicalDetails: { ...(td ?? {}), province },
          };
        }
      }
      return test;
    });

    return new Response(JSON.stringify({ obligationTests: enrichedObligationTests as any, total } satisfies OutputType));
  } catch (error) {
    console.error("Error listing creditor obligation tests:", error);
    return handleEndpointError(error);
  }
}