import { z } from "zod";

import { Selectable } from "kysely";
import { CreditorObligationTest } from "../../helpers/schema";

export const CREDITOR_VALIDATION_LIST_DEFAULT_LIMIT = 50;
export const CREDITOR_VALIDATION_LIST_MAX_LIMIT = 100;

export const schema = z.object({
  creditorId: z.number().optional(),
  obligationState: z.enum(['CHALLENGED', 'INSUFFICIENT_RESPONSE', 'NO_RESPONSE', 'OBLIGATION_PENDING', 'PROCEDURALLY_EXHAUSTED', 'ADDRESSED_VIA_LINKED_DISPUTE']).optional(),
  tradelineId: z.number().optional(),
  limit: z.coerce.number().int().min(1).max(CREDITOR_VALIDATION_LIST_MAX_LIMIT).default(CREDITOR_VALIDATION_LIST_DEFAULT_LIMIT),
  offset: z.coerce.number().int().min(0).default(0),
});

export type InputType = Partial<z.infer<typeof schema>>;

export type ObligationTestWithDetails = Omit<Selectable<CreditorObligationTest>, 'id' | 'creditorId' | 'obligationType' | 'obligationState' | 'obligationSequence' | 'disputeVector' | 'lastChallengeDate' | 'responseDeadline' | 'responsesReceived' | 'metro2Version' | 'statutoryBasis' | 'omissions' | 'validationStatus' | 'escalationPath' | 'notes' | 'lastTestDate' | 'tradelineId' | 'createdAt' | 'updatedAt' | 'violationCategory' | 'confidenceScore' | 'autoGenerated' | 'userExplanation' | 'technicalDetails' | 'recommendedAction' | 'detectedAt'> & {
  id: number;
  creditorId: number | null;
  obligationType: Selectable<CreditorObligationTest>['obligationType'];
  obligationState: Selectable<CreditorObligationTest>['obligationState'];
  obligationSequence: number | null;
  disputeVector: string | null;
  lastChallengeDate: Date | null;
  responseDeadline: Date | null;
  responsesReceived: number | null;
  metro2Version: string | null;
  statutoryBasis: string | null;
  omissions: string | null;
  validationStatus: string | null;
  escalationPath: string | null;
  notes: string | null;
  lastTestDate: Date | null;
  tradelineId: number | null;
  createdAt: Date | null;
  updatedAt: Date | null;
  violationCategory: Selectable<CreditorObligationTest>['violationCategory'];
  confidenceScore: number | null;
  autoGenerated: boolean | null;
  userExplanation: string | null;
  technicalDetails: any | null;
  recommendedAction: string | null;
  detectedAt: Date | null;
  userStatus: string;
  userStatusReason: string | null;
  userStatusUpdatedAt: Date | null;
  creditorName: string | null;
  tradelineAccountNumber: string | null;
  tradelineDisplayStatus: string | null;
  tradelineCurrentBalance: string | number | null;
  tradelineBalance: string | number | null;
  tradelineBureauName: string | null;
  tradelineAccountType: string | null;
  tradelineCollectionAgencyName: string | null;
  tradelineOriginalCreditorName: string | null;
  tradelineIsCollectionAccount: boolean | null;
};

export type OutputType = {
  obligationTests: ObligationTestWithDetails[];
  total: number;
};

export const getCreditorValidationList = async (params: InputType = {}, init?: RequestInit): Promise<OutputType> => {
  const url = new URL(`/_api/creditor-validation/list`, typeof window !== 'undefined' ? window.location.origin : 'http://localhost');

  if (params.creditorId !== undefined) url.searchParams.append('creditorId', params.creditorId.toString());
  if (params.obligationState !== undefined) url.searchParams.append('obligationState', params.obligationState);
  if (params.tradelineId !== undefined) url.searchParams.append('tradelineId', params.tradelineId.toString());
  if (params.limit !== undefined) url.searchParams.append('limit', params.limit.toString());
  if (params.offset !== undefined) url.searchParams.append('offset', params.offset.toString());

  const result = await fetch(url.toString(), {
    method: "GET",
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });

  if (!result.ok) {
    const errorObject = JSON.parse(await result.text());
    throw new Error(errorObject.error);
  }
  return JSON.parse(await result.text());
};
