import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";

type FindingRow = {
  id: number;
  tradelineId: number;
  autoGenerated: boolean | null;
  userStatus: string;
  validationStatus: string | null;
  violationCategory: string | null;
  userExplanation: string | null;
  technicalDetails: Record<string, unknown> | null;
};

type MockState = {
  committedRows: FindingRow[];
  nextId: number;
  insertCount: number;
  failOnInsertAt: number | null;
  lockTail: Promise<void>;
  lockAcquisitions: number;
  onAfterDelete?: (committedRows: FindingRow[], transactionRows: FindingRow[]) => void;
};

type MockTransactionContext = {
  state: MockState;
  rows: FindingRow[];
  releases: Array<() => void>;
};

function cloneRows(rows: FindingRow[]): FindingRow[] {
  return JSON.parse(JSON.stringify(rows));
}

function deferred(): { promise: Promise<void>; resolve: () => void } {
  let resolve!: () => void;
  const promise = new Promise<void>((innerResolve) => {
    resolve = innerResolve;
  });
  return { promise, resolve };
}

async function acquireTradelineLock(context: MockTransactionContext): Promise<void> {
  const previous = context.state.lockTail;
  const next = deferred();
  context.state.lockTail = previous.then(() => next.promise);
  await previous;
  context.releases.push(next.resolve);
  context.state.lockAcquisitions += 1;
  context.rows = cloneRows(context.state.committedRows);
}

function valueFor(row: FindingRow, column: string): unknown {
  if (column.endsWith(".id") || column === "id") return row.id;
  if (column.endsWith(".tradelineId") || column === "tradelineId") return row.tradelineId;
  if (column.endsWith(".autoGenerated") || column === "autoGenerated") return row.autoGenerated;
  if (column.endsWith(".userStatus") || column === "userStatus") return row.userStatus;
  return (row as Record<string, unknown>)[column];
}

function matches(row: FindingRow, filters: Array<[string, string, unknown]>): boolean {
  return filters.every(([column, op, expected]) => {
    const actual = valueFor(row, column);
    if (op === "=") return actual === expected;
    if (op === "!=") return actual !== expected;
    if (op === "in") return Array.isArray(expected) && expected.includes(actual);
    throw new Error(`Unsupported mock filter operator: ${op}`);
  });
}

function selectBuilder(context: MockTransactionContext, table: string) {
  const filters: Array<[string, string, unknown]> = [];
  let lockForUpdate = false;
  const builder = {
    select: () => builder,
    where: (column: string, op: string, value: unknown) => {
      filters.push([column, op, value]);
      return builder;
    },
    forUpdate: () => {
      lockForUpdate = true;
      return builder;
    },
    executeTakeFirst: async () => {
      if (table === "tradeline") {
        if (lockForUpdate) await acquireTradelineLock(context);
        return { userId: 1, creditorId: 44 };
      }
      if (table !== "creditorObligationTest") return undefined;
      return context.rows.filter((row) => matches(row, filters))[0];
    },
    execute: async () => {
      if (table !== "creditorObligationTest") return [];
      return context.rows.filter((row) => matches(row, filters));
    },
  };
  return builder;
}

function deleteBuilder(context: MockTransactionContext, table: string) {
  const filters: Array<[string, string, unknown]> = [];
  const builder = {
    where: (column: string, op: string, value: unknown) => {
      filters.push([column, op, value]);
      return builder;
    },
    execute: async () => {
      if (table !== "creditorObligationTest") return [{ numDeletedRows: 0 }];
      const before = context.rows.length;
      context.rows = context.rows.filter((row) => !matches(row, filters));
      const deleted = before - context.rows.length;
      context.state.onAfterDelete?.(cloneRows(context.state.committedRows), cloneRows(context.rows));
      return [{ numDeletedRows: BigInt(deleted) }];
    },
  };
  return builder;
}

function insertBuilder(context: MockTransactionContext, table: string) {
  let pendingValues: Record<string, unknown> | null = null;
  const builder = {
    values: (values: Record<string, unknown>) => {
      pendingValues = values;
      return builder;
    },
    returning: () => builder,
    executeTakeFirst: async () => {
      if (table !== "creditorObligationTest" || !pendingValues) return undefined;
      context.state.insertCount += 1;
      if (context.state.failOnInsertAt === context.state.insertCount) {
        throw new Error("SIMULATED_INSERT_FAILURE");
      }
      const id = context.state.nextId;
      context.state.nextId += 1;
      context.rows.push({
        id,
        tradelineId: Number(pendingValues.tradelineId),
        autoGenerated: pendingValues.autoGenerated as boolean,
        userStatus: "active",
        validationStatus: pendingValues.validationStatus as string | null,
        violationCategory: pendingValues.violationCategory as string,
        userExplanation: pendingValues.userExplanation as string,
        technicalDetails: pendingValues.technicalDetails as Record<string, unknown>,
      });
      return { id };
    },
  };
  return builder;
}

function createMockDb(state: MockState) {
  return {
    transaction: () => ({
      execute: async <T>(callback: (trx: any) => Promise<T>): Promise<T> => {
        const context: MockTransactionContext = {
          state,
          rows: cloneRows(state.committedRows),
          releases: [],
        };
        const trx = {
          selectFrom: (table: string) => selectBuilder(context, table),
          deleteFrom: (table: string) => deleteBuilder(context, table),
          insertInto: (table: string) => insertBuilder(context, table),
        };
        try {
          const result = await callback(trx);
          state.committedRows = cloneRows(context.rows);
          return result;
        } finally {
          for (const release of context.releases.reverse()) release();
        }
      },
    }),
    selectFrom: (table: string) =>
      selectBuilder({
        state,
        rows: cloneRows(state.committedRows),
        releases: [],
      }, table),
  };
}

function state(rows: FindingRow[], overrides: Partial<MockState> = {}): MockState {
  return {
    committedRows: cloneRows(rows),
    nextId: 100,
    insertCount: 0,
    failOnInsertAt: null,
    lockTail: Promise.resolve(),
    lockAcquisitions: 0,
    ...overrides,
  };
}

function existingFinding(overrides: Partial<FindingRow>): FindingRow {
  return {
    id: 1,
    tradelineId: 501,
    autoGenerated: true,
    userStatus: "active",
    validationStatus: "PENDING",
    violationCategory: "BALANCE_EXCEEDS_CREDIT_LIMIT",
    userExplanation: "old auto finding",
    technicalDetails: { sourceReportArtifactId: 7001 },
    ...overrides,
  };
}

function violation(userExplanation: string, category = "BALANCE_EXCEEDS_CREDIT_LIMIT") {
  return {
    violationCategory: category,
    severity: "HIGH",
    confidenceScore: 95,
    userExplanation,
    technicalDetails: {
      evidenceReference: "Source report #7; field: balance; page 2",
      regulationReferences: [{ statute: "FCRA", citation: "1681s-2", sourceQuality: "official" }],
    },
    recommendedAction: "Review and correct if unsupported.",
    responsibleEntity: "CREDITOR",
  };
}

async function loadPersistViolations(
  mockDb: unknown,
  evaluateViolationPacketConfidenceGate = vi.fn(() => ({
    blockerCode: null,
    packetReady: true,
    message: "This compliance finding is available for dispute review.",
  })),
) {
  vi.resetModules();
  vi.doMock("../../helpers/db", () => ({ db: mockDb }));
  vi.doMock("../../helpers/complianceFindingNormalizer", () => ({
    normalizeDetectedViolations: (violations: unknown[]) => violations,
  }));
  vi.doMock("../../helpers/complianceFindingEligibility", () => ({
    annotateDetectedViolationsEligibility: (violations: unknown[]) => violations,
  }));
  vi.doMock("../../helpers/violationRuleEvidence", () => ({
    enrichDetectedViolationsRuleEvidence: (violations: unknown[]) => violations,
    enrichDetectedViolationDefensibilityMetadata: (violation: any) => violation,
    enrichDetectedViolationsDefensibilityMetadata: (violations: unknown[]) => violations,
    getDeterministicViolationStatutoryBasis: () => "FCRA 1681s-2",
  }));
  vi.doMock("../../helpers/violationPacketConfidenceGate", () => ({
    evaluateParserConfidenceGateFromArtifactData: () => ({
      status: "confirmed",
      packetReady: true,
      reasonCodes: [],
    }),
    evaluateViolationPacketConfidenceGate,
  }));
  return import("../../helpers/complianceScanner");
}

function activeAutoRows(rows: FindingRow[]): FindingRow[] {
  return rows.filter((row) => row.autoGenerated === true && row.userStatus === "active");
}

afterEach(() => {
  vi.resetModules();
  vi.restoreAllMocks();
});

describe("atomic compliance finding replacement", () => {
  it("uses a transaction and tradeline row lock for active auto finding replacement", () => {
    const scanner = readFileSync(resolve(process.cwd(), "helpers/complianceScanner.tsx"), "utf8");
    const persistStart = scanner.indexOf("export async function persistViolations");
    const persistSource = scanner.slice(persistStart, scanner.indexOf("/**", persistStart + 1));

    expect(persistSource).toContain("db.transaction().execute");
    expect(persistSource).toContain(".forUpdate()");
    expect(persistSource).toContain(".deleteFrom(\"creditorObligationTest\")");
    expect(persistSource).toContain(".insertInto(\"creditorObligationTest\")");
    expect(persistSource).not.toContain("Continue with other violations even if one fails");
  });

  it("simulated insert failure preserves previous active findings", async () => {
    const mockState = state([
      existingFinding({ id: 10, userExplanation: "old auto finding" }),
      existingFinding({ id: 11, autoGenerated: false, userExplanation: "manual admin finding" }),
    ], { failOnInsertAt: 1 });
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState));

    await expect(persistViolations([violation("new auto finding") as any], 501)).rejects.toThrow("SIMULATED_INSERT_FAILURE");

    expect(mockState.committedRows.map((row) => row.userExplanation).sort()).toEqual([
      "manual admin finding",
      "old auto finding",
    ]);
  });

  it("successful scan atomically replaces previous auto findings", async () => {
    const mockState = state([
      existingFinding({ id: 10, userExplanation: "old auto finding" }),
    ]);
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState));

    const ids = await persistViolations([
      violation("new auto finding A") as any,
      violation("new auto finding B", "DATE_REPORTED_LOGIC") as any,
    ], 501);

    expect(ids).toEqual([100, 101]);
    expect(activeAutoRows(mockState.committedRows).map((row) => row.userExplanation).sort()).toEqual([
      "new auto finding A",
      "new auto finding B",
    ]);
    expect(mockState.committedRows.some((row) => row.userExplanation === "old auto finding")).toBe(false);
  });

  it("manual/admin and non-active findings survive replacement", async () => {
    const mockState = state([
      existingFinding({ id: 10, userExplanation: "old auto finding" }),
      existingFinding({ id: 11, autoGenerated: false, userExplanation: "manual active finding" }),
      existingFinding({ id: 12, userStatus: "dismissed", userExplanation: "dismissed auto finding" }),
    ]);
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState));

    await persistViolations([violation("new auto finding") as any], 501);

    expect(mockState.committedRows.map((row) => row.userExplanation).sort()).toEqual([
      "dismissed auto finding",
      "manual active finding",
      "new auto finding",
    ]);
  });

  it("marks auto-generated findings that fail the packet gate as needing review", async () => {
    const mockState = state([]);
    const packetGate = vi.fn(() => ({
      blockerCode: "violation_needs_review",
      packetReady: false,
      message: "Required source-report evidence is missing for this finding.",
    }));
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState), packetGate);

    await persistViolations([violation("weak auto finding") as any], 501);

    expect(packetGate).toHaveBeenCalledWith(expect.objectContaining({
      autoGenerated: true,
      userStatus: "active",
    }));
    expect(mockState.committedRows).toContainEqual(expect.objectContaining({
      userExplanation: "weak auto finding",
      autoGenerated: true,
      validationStatus: "NEEDS_USER_REVIEW",
    }));
  });

  it("packet readiness readers do not observe the uncommitted partial replacement set", async () => {
    const mockState = state([
      existingFinding({ id: 10, userExplanation: "old packet-ready finding" }),
    ]);
    mockState.onAfterDelete = (committedRows, transactionRows) => {
      expect(activeAutoRows(transactionRows)).toEqual([]);
      expect(activeAutoRows(committedRows).map((row) => row.userExplanation)).toEqual(["old packet-ready finding"]);
    };
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState));

    await persistViolations([violation("new packet-ready finding") as any], 501);

    expect(activeAutoRows(mockState.committedRows).map((row) => row.userExplanation)).toEqual(["new packet-ready finding"]);
  });

  it("concurrent scan simulation does not produce mixed active truth", async () => {
    const mockState = state([
      existingFinding({ id: 10, userExplanation: "old auto finding" }),
      existingFinding({ id: 11, autoGenerated: false, userExplanation: "manual active finding" }),
    ]);
    const { persistViolations } = await loadPersistViolations(createMockDb(mockState));

    await Promise.all([
      persistViolations([violation("first scan finding") as any], 501),
      persistViolations([violation("second scan finding") as any], 501),
    ]);

    expect(mockState.lockAcquisitions).toBe(2);
    expect(activeAutoRows(mockState.committedRows).map((row) => row.userExplanation)).toEqual(["second scan finding"]);
    expect(mockState.committedRows.map((row) => row.userExplanation)).toContain("manual active finding");
  });
});
